<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
       "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Language" content="de">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
<title>Contribute | Wikimedia Fundraising</title>
<link rel="stylesheet" href="css/styles.css" type="text/css">
<style type="text/css">
body {
 margin: 0px;
 padding: 0px;
 background-image:url(images/background.gif); background-repeat:repeat-y;
 background-position:center;
 background-color:#006699; 
 font-family: Verdana, Arial, Sans-Serif;
 font-size: 10pt;
}
</style>
</head>

<body>
<center>

<table border="0" cellspacing="0" cellpadding="0" style="table-layout:fixed;"><tr><td width="886" height="123" valign="middle" style="background-image:url(images/header-logos.jpg);"><div style="margin-left:160px; font-size:22px; font-weight:bold; color:#484848; text-align:left;">

You can help Wikipedia<br>change the world

</div></td></tr><tr><td width="886" height="15" style="background-image:url(images/header-border.gif); background-repeat:repeat-x;"></td></tr></table>


