#!/bin/bash

SCALER_SERVICE_IP=10.2.1.21

set -e 

case "$1" in
	configure)
		# Disable bitmap fonts in fontconfig...
		# They can cause problems with fonts like "Helvetica",
		# since they look horrible and don't scale correctly.
		if ! [ -e /etc/fonts/conf.d/70-no-bitmaps.conf ]
		then
		  ln -s ../conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf
		fi
		if -e [ /etc/fonts/conf.d/70-yes-bitmaps.conf ]
		then
			rm -f /etc/fonts/conf.d/70-yes-bitmaps.conf
		fi
		
		if ! grep -qF $SCALER_SERVICE_IP /etc/default/wikimedia-lvs-realserver
		then
			echo "
### START: Added by wikimedia-task-scaler
LVS_SERVICE_IPS=\"$SCALER_SERVICE_IP \$LVS_SERVICE_IPS\"
### END: Added by wikimedia-task-scaler
" >> /etc/default/wikimedia-lvs-realserver
		fi

		# Bring up the interface
		IFACE=lo /etc/network/if-up.d/wikimedia-lvs-realserver

		# Restart apache with -DSCALER
		/etc/init.d/apache2 restart || true
		;;
    abort-upgrade|abort-remove|abort-deconfigure)

    	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

