.ig
WikiTeX: expansible LaTeX module for MediaWiki
Copyright (C) 2004-7 Peter Danenberg
See doc/COPYING for details.
..
.so heading.ms
.XH 1 Copyright
.LP
WikiTeX: expansible LaTeX module for MediaWiki
.br
Copyright \(co 2004-7 Peter Danenberg
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
