#!/bin/bash
#
# Shell script that shows or updates the current DNS geobackend "scenario",
# e.g. "normal", "knams_down", etc.
#
# Written on 2007/01/13 by Mark Bergsma <mark@nedworks.org>

set -e

CONFFILE=/etc/default/wikimedia-task-dns-auth
NAMESERVERS=""
POWERDNSDIR=/etc/powerdns
SCRIPTDIR=/usr/lib/wikimedia-task-dns-auth/bin

PATH=/bin:/usr/bin:/usr/local/bin

# Source the configuration file
[ -f $CONFFILE ] && source $CONFFILE

# Read the current scenario
SCENARIO=$(readlink $POWERDNSDIR/geomaps | cut -d '/' -f 2 || true)

if [ -z "$SCENARIO" ] && [ -z "$1" ]
then
	echo "No scenario set, symlink $POWERDNSDIR/geomaps doesn't exist."
	exit 1
fi

if [ -z "$1" ]
then
	echo "Current scenario: $SCENARIO"
	echo "Available scenarios:"
	ls $POWERDNSDIR/scenarios
	exit
fi

NEWSCENARIO=$1
echo "Setting scenario to $NEWSCENARIO."

if [ ! -d $POWERDNSDIR/scenarios/$NEWSCENARIO ]
then
	echo "Scenario directory $POWERDNSDIR/scenarios/$NEWSCENARIO does not exist, keeping current scenario $SCENARIO."
	exit 1
fi

rm -f $POWERDNSDIR/geomaps
ln -s scenarios/$NEWSCENARIO $POWERDNSDIR/geomaps

echo "Done, now please run authdns-update!"
