#!/bin/sh
# chkconfig: 2345 20 80
# description: gmetricd startup script
#
GMETRICD=/usr/sbin/gmetricd

. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
	start)
		if [ ! -f $GMETRICD ];then
			echo gmetricd: no executable file
			exit 1
		fi
		PID=`pidofproc gmetricd`
		if [ ! -z $PID ];then
			echo gmetricd: already running
			exit 1
		fi
		echo -n "Starting gmetricd: "

		daemon $GMETRICD
		RETVAL=$?
		echo
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/gmetricd
		;;

	stop)
		echo -n "Shutting down gmetricd: "
		killproc gmetricd
		RETVAL=$?
		echo
		[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/gmetricd
		;;

	restart|reload)
		$0 stop
		$0 start
		RETVAL=$?
		;;
	status)
		status gmetricd
		RETVAL=$?
		;;
		*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
esac

exit $RETVAL

