<?php
/**
 * Internationalisation for Uniwiki/Layouts extension
 *
 * @file
 * @ingroup Extensions
 */

$messages = array();

/** English */
$messages['en'] = array(
	'layouts-desc' => 'Populate newly-created pages with editable "layouts" to encourage a common structure for pages',
	'layouts_title' => 'Create a page',
	'layouts_chooselayout' => 'Choose a layout for $1:',
	'layouts_nolayout' => 'No layout',
	'layouts_continue' => 'Continue',
	'layouts_choosecategory' => 'Choose a category for $1:',
	'layouts_unknown' => 'Unknown',
	'layouts_tagline' => 'This page was generated by the \'\'\'$1\'\'\' layout.',
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags'
);

/** Message documentation (Message documentation)
 * @author Purodha
 */
$messages['qqq'] = array(
	'layouts-desc' => 'Short description of this extension, shown on [[Special:Version]].
Do not translate or change links.',
);

/** Egyptian Spoken Arabic (مصرى)
 * @author Ramsis II
 */
$messages['arz'] = array(
	'layouts_title' => 'ابتدي صفحه',
	'layouts_continue' => 'استمر',
	'layouts_choosecategory' => 'اختار تصنيف لـ $1:',
	'layouts_unknown' => 'مش معروف',
);

/** Belarusian (Taraškievica orthography) (Беларуская (тарашкевіца))
 * @author EugeneZelenko
 */
$messages['be-tarask'] = array(
	'layouts_title' => 'Стварыць старонку',
);

/** Bulgarian (Български)
 * @author DCLXVI
 */
$messages['bg'] = array(
	'layouts_title' => 'Създаване на страница',
	'layouts_continue' => 'Продължаване',
	'layouts_choosecategory' => 'Избиране на категория за $1:',
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Bosnian (Bosanski)
 * @author CERminator
 */
$messages['bs'] = array(
	'layouts_title' => 'Napravi stranicu',
	'layouts_continue' => 'Nastavi',
	'layouts_choosecategory' => 'Izaberi kategoriju za $1:',
	'layouts_unknown' => 'Nepoznato',
);

/** German (Deutsch) */
$messages['de'] = array(
	'layouts_title' => 'Neue Seite erstellen',
	'layouts_chooselayout' => 'Suche ein Format für $1 aus:',
	'layouts_nolayout' => 'Kein Format',
	'layouts_continue' => 'Weiter',
	'layouts_choosecategory' => 'Suche eine Kategorie für $1 aus:',
	'layouts_unknown' => 'Unbekannt',
	'layouts_tagline' => "Diese Seite wurde mit dem '''$1'''-Layout erstellt.",
);

/** Esperanto (Esperanto)
 * @author Yekrats
 */
$messages['eo'] = array(
	'layouts_title' => 'Krei paĝon',
	'layouts_chooselayout' => 'Elektu aspekton por $1:',
	'layouts_continue' => 'Daŭrigi',
	'layouts_choosecategory' => 'Selekti kategorion por $1:',
	'layouts_unknown' => 'Nekonata',
);

/** Spanish (Español) */
$messages['es'] = array(
	'layouts_title' => 'Crear una página',
	'layouts_chooselayout' => 'Selecciona un Diseño para $1:',
	'layouts_nolayout' => 'Sin diseño',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Elige una Categoría para $1:',
	'layouts_unknown' => 'Desconocido',
	'layouts_tagline' => 'Esta página se generó con el diseño <strong>$1</strong>.',
);

/** French (Français)
 * @author Grondin
 * @author IAlex
 * @author Sherbrooke
 */
$messages['fr'] = array(
	'layouts-desc' => "Peupler les pages nouvellement créées avec des « mises en page » modifiables afin d'encourager une structure commune à toutes les pages",
	'layouts_title' => 'Créer une page',
	'layouts_chooselayout' => 'Choisir une mise en page pour $1 :',
	'layouts_nolayout' => 'Aucune mise en page',
	'layouts_continue' => 'Continuer',
	'layouts_choosecategory' => 'Choisir une catégorie pour $1 :',
	'layouts_unknown' => 'Inconnu',
	'layouts_tagline' => "Cette page a été générée avec la mise en page '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Irish (Gaeilge)
 * @author Alison
 */
$messages['ga'] = array(
	'layouts_continue' => 'Lean',
);

/** Galician (Galego)
 * @author Toliño
 */
$messages['gl'] = array(
	'layouts-desc' => 'Poboar as páxinas novas creadas con distribucións editables para fomentar unha estrutura común para as páxinas',
	'layouts_title' => 'Crear unha páxina',
	'layouts_chooselayout' => 'Escolla unha distribución para "$1":',
	'layouts_nolayout' => 'Sen distribución',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Escolla unha categoría para "$1":',
	'layouts_unknown' => 'Descoñecido',
	'layouts_tagline' => "Esta páxina foi xerada coa distribución '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Hebrew (עברית)
 * @author Rotemliss
 * @author YaronSh
 */
$messages['he'] = array(
	'layouts-desc' => 'הוספת "פריסות" הניתנות לעריכה לדפים חדשים כדי לעודד מבנה נפוץ לדפים',
	'layouts_title' => 'יצירת דף',
	'layouts_chooselayout' => 'בחרו בפריסה עבור $1:',
	'layouts_nolayout' => 'ללא פריסה',
	'layouts_continue' => 'המשך',
	'layouts_choosecategory' => 'בחרו קטגוריה עבור $1:',
	'layouts_unknown' => 'לא ידוע',
	'layouts_tagline' => "הדף נוצר על ידי הפריסה '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Upper Sorbian (Hornjoserbsce)
 * @author Michawiki
 */
$messages['hsb'] = array(
	'layouts-desc' => 'Wuhotuj nowowutworjene strony z wobdźěłujomne  "wuhotowanja", zo by jednotnu strukturu za strony spěchował',
	'layouts_title' => 'Stronu wutworić',
	'layouts_chooselayout' => 'Wubjer wuhotowanje za $1:',
	'layouts_nolayout' => 'Žane wuhotowanje',
	'layouts_continue' => 'Dale',
	'layouts_choosecategory' => 'Wubjer kategoriju za $1:',
	'layouts_unknown' => 'Njeznaty',
	'layouts_tagline' => "Tuta strona bu z wuhotowanjom '''$1''' wutworjena.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Interlingua (Interlingua)
 * @author McDutchie
 */
$messages['ia'] = array(
	'layouts-desc' => 'Insere in cata pagina novemente create un "disposition" modificabile pro incoragiar un structura commun a tote le paginas',
	'layouts_title' => 'Crear un pagina',
	'layouts_chooselayout' => 'Selige un disposition pro $1:',
	'layouts_nolayout' => 'Nulle disposition',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Selige un categoria pro $1:',
	'layouts_unknown' => 'Incognite',
	'layouts_tagline' => "Iste pagina ha essite generate con le disposition '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Modificaretiquettasdepaginas',
);

/** Javanese (Basa Jawa)
 * @author Pras
 */
$messages['jv'] = array(
	'layouts_title' => 'Gawé kaca',
	'layouts_chooselayout' => "Pilih rancangan(''layout'') kanggo $1:",
	'layouts_nolayout' => "Ora ana rancangan (''layout'')",
	'layouts_continue' => 'Terusaké',
	'layouts_choosecategory' => 'Pilih kategori kanggo $1:',
	'layouts_unknown' => 'Ora diweruhi',
	'layouts_tagline' => "Kaca iki kacipta nganggo rancangan '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Tagkacasunting',
);

/** Khmer (ភាសាខ្មែរ)
 * @author Thearith
 */
$messages['km'] = array(
	'layouts_title' => 'បង្កើត​ទំព័រ​មួយ',
	'layouts_chooselayout' => 'ជ្រើសរើស​ប្លង់​មួយ​សម្រាប់ $1​៖',
	'layouts_nolayout' => 'មិនមាន​ប្លង់​ទេ',
	'layouts_continue' => 'បន្ត',
	'layouts_choosecategory' => 'ជ្រើរើស​ចំណាត់ក្រុម​មួយ​សម្រាប់ $1​៖',
	'layouts_unknown' => 'មិន​ត្រូវ​បាន​ស្គាល់',
	'layouts_tagline' => "ទំព័រ​នេះ​ត្រូវ​បាន​បង្កើតឡើង​ដោយ​ប្លង់ '''$1''' ។",
);

/** Ripoarisch (Ripoarisch)
 * @author Purodha
 */
$messages['ksh'] = array(
	'layouts-desc' => 'Deit op jede neu aanjelaate Sigg en änderbaa „Läj_aut“ drop, ön ene einheitlijje Opbou för de Sigge ze fördere.',
	'layouts_title' => 'En neu Sigg aanlääje',
);

/** Luxembourgish (Lëtzebuergesch)
 * @author Robby
 */
$messages['lb'] = array(
	'layouts_title' => 'Eng Säit uleeën',
	'layouts_chooselayout' => 'E Layout fir $1 eraussichen:',
	'layouts_nolayout' => 'Kee Layout',
	'layouts_continue' => 'Weider',
	'layouts_choosecategory' => 'Wielt eng Kategorie fir $1:',
	'layouts_unknown' => 'Onbekannt',
);

/** Dutch (Nederlands)
 * @author Siebrand
 */
$messages['nl'] = array(
	'layouts-desc' => "Vult nieuw aangemaakte pagina's met bewerkbare sjablonen om een gelijkvormige structuur voor pagina's aan te moedigen",
	'layouts_title' => 'Pagina aanmaken',
	'layouts_chooselayout' => 'Kies een sjabloon voor $1:',
	'layouts_nolayout' => 'Geen sjabloon',
	'layouts_continue' => 'Volgende',
	'layouts_choosecategory' => 'Kies een categorie voor $1:',
	'layouts_unknown' => 'Onbekend',
	'layouts_tagline' => "Deze pagina is aangemaakt met het sjabloon '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagelabels',
);

/** Norwegian Nynorsk (‪Norsk (nynorsk)‬)
 * @author Harald Khan
 */
$messages['nn'] = array(
	'layouts_title' => 'Opprett ei sida',
);

/** Occitan (Occitan)
 * @author Cedric31
 */
$messages['oc'] = array(
	'layouts-desc' => 'Poblar las paginas creadas novèlament amb de « mesas en pagina » modificablas per encoratjar una estructura comuna a totas las paginas',
	'layouts_title' => 'Crear una pagina',
	'layouts_chooselayout' => 'Causir una mesa en pagina per $1 :',
	'layouts_nolayout' => 'Pas cap de mesa en pagina',
	'layouts_continue' => 'Contunhar',
	'layouts_choosecategory' => 'Causir una categoria per $1 :',
	'layouts_unknown' => 'Desconegut',
	'layouts_tagline' => "Aquesta pagina es estada generida amb la mesa en pagina '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Pashto (پښتو)
 * @author Ahmed-Najib-Biabani-Ibrahimkhel
 */
$messages['ps'] = array(
	'layouts_title' => 'يو مخ جوړول',
	'layouts_choosecategory' => 'د $1 لپاره يوه وېشنيزه وټاکۍ:',
	'layouts_unknown' => 'ناجوت',
);

/** Brazilian Portuguese (Português do Brasil) */
$messages['pt-br'] = array(
	'layouts_title' => 'Criar uma página',
	'layouts_chooselayout' => 'Escolher um Layout para o $1:',
	'layouts_nolayout' => 'Sem layout',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Escolher uma Categoria para o $1:',
	'layouts_unknown' => 'Desconhecido',
	'layouts_tagline' => 'Esta página foi gerada pelo layout <strong>$1</strong>.',
);

/** Romanian (Română)
 * @author KlaudiuMihaila
 */
$messages['ro'] = array(
	'layouts_title' => 'Creează o pagină',
	'layouts_continue' => 'Continuă',
	'layouts_choosecategory' => 'Alegeţi o categorie pentru $1:',
);

/** Russian (Русский)
 * @author Ferrer
 * @author Александр Сигачёв
 */
$messages['ru'] = array(
	'layouts-desc' => 'Заполняет вновь создаваемые страницы редактируемыми «макетами» с целью по поддерживать типовую структуру страниц.',
	'layouts_title' => 'Создать страницу',
	'layouts_chooselayout' => 'Выбор макета для $1:',
	'layouts_nolayout' => 'Нет макета',
	'layouts_continue' => 'Продолжить',
	'layouts_choosecategory' => 'Выбор категории для $1:',
	'layouts_unknown' => 'Неизвестно',
	'layouts_tagline' => "Эта страница была создана с помощью макета '''$1'''.",
);

/** Slovak (Slovenčina)
 * @author Helix84
 */
$messages['sk'] = array(
	'layouts-desc' => 'Naplní novo vytvorené stránky rozloženiami, ktoré možno upravovať, aby sa posilnila spoločná štruktúra stránok',
	'layouts_title' => 'Vytvoriť stránku',
	'layouts_chooselayout' => 'Vyberte rozloženie pre $1:',
	'layouts_nolayout' => 'Žiadne rozloženie',
	'layouts_continue' => 'Pokračovať',
	'layouts_choosecategory' => 'Vyberte kategóriu pre $1:',
	'layouts_unknown' => 'Neznáme',
	'layouts_tagline' => "Túto stránku vytvorilo rozloženie '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Swedish (Svenska)
 * @author Najami
 */
$messages['sv'] = array(
	'layouts_title' => 'Skapa en sida',
	'layouts_chooselayout' => 'Välj ett utseende för $1:',
	'layouts_nolayout' => 'Inget utseende',
	'layouts_continue' => 'Fortsätt',
	'layouts_choosecategory' => 'Välj en kategori för $1:',
	'layouts_unknown' => 'Okänd',
);

/** Vietnamese (Tiếng Việt)
 * @author Minh Nguyen
 */
$messages['vi'] = array(
	'layouts_title' => 'Tạo trang',
	'layouts_continue' => 'Tiếp tục',
	'layouts_unknown' => 'Không biết',
);

