<?php
/* vim: noet ts=4 sw=4
 * http://www.mediawiki.org/wiki/Extension:Uniwiki_Layouts
 * http://www.gnu.org/licenses/gpl-3.0.txt */

if (!defined("MEDIAWIKI"))
	die();

$wgLayoutsMessages = array();
$wgLayoutsMessages['en'] = array(
	'layouts_title'          => "Create a page",
	'layouts_chooselayout'   => "Choose a Layout for $1:",
	'layouts_nolayout'       => "No layout",
	'layouts_continue'       => "Continue",
	'layouts_choosecategory' => "Choose a Category for $1:",
	'layouts_unknown'        => "UNKNOWN",
	'layouts_tagline'        => "This page was generated by the <strong>$1</strong> layout."
);

$wgLayoutsMessages['es'] = array(
        'layouts_title'          => "Crear una página",
        'layouts_chooselayout'   => "Selecciona un Diseño para $1:",
        'layouts_nolayout'       => "Sin diseño",
        'layouts_continue'       => "Continuar",
        'layouts_choosecategory' => "Elige una Categoría para $1:",
        'layouts_unknown'        => "DESCONOCIDO",
        'layouts_tagline'        => "Esta página se generó con el diseño <strong>$1</strong>."
);

$wgLayoutsMessages['de'] = array(
	'layouts_title'          => "Neue Seite erstellen",
	'layouts_chooselayout'   => "Suche ein Format aus für $1:",
	'layouts_nolayout'       => "Kein Format",
	'layouts_continue'       => "Weiter",
	'layouts_choosecategory' => "Suche ein Club aus für $1:",
	'layouts_unknown'        => "UNBEKANNT",
	'layouts_tagline'        => "Diese Seite wurde mit dem <strong>$1</strong> Layout erstellt."
);

$wgLayoutsMessages['pt-br'] = array(
        'layouts_title'          => "Criar uma página",
        'layouts_chooselayout'   => "Escolher um Layout para o $1:",
        'layouts_nolayout'       => "Sem layout",
        'layouts_continue'       => "Continuar",
        'layouts_choosecategory' => "Escolher uma Categoria para o $1:",
        'layouts_unknown'        => "DESCONHECIDO",
        'layouts_tagline'        => "Esta página foi gerada pelo layout <strong>$1</strong>."
);
