<?php
/**
 * Internationalisation for Uniwiki/Layouts extension
 *
 * @file
 * @ingroup Extensions
 */

$messages = array();

/** English */
$messages['en'] = array(
	'layouts-desc' => 'Populate newly-created pages with editable "layouts" to encourage a common structure for pages',
	'layouts_title' => 'Create a page',
	'layouts_chooselayout' => 'Choose a layout for $1:',
	'layouts_nolayout' => 'No layout',
	'layouts_continue' => 'Continue',
	'layouts_choosecategory' => 'Choose a category for $1:',
	'layouts_unknown' => 'Unknown',
	'layouts_tagline' => 'This page was generated by the \'\'\'$1\'\'\' layout.',
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags'
);

$messages['es'] = array(
	'layouts_title' => 'Crear una página',
	'layouts_chooselayout' => 'Selecciona un Diseño para $1:',
	'layouts_nolayout' => 'Sin diseño',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Elige una Categoría para $1:',
	'layouts_unknown' => 'Desconocido',
	'layouts_tagline' => 'Esta página se generó con el diseño <strong>$1</strong>.',
);

$messages['de'] = array(
	'layouts_title' => 'Neue Seite erstellen',
	'layouts_chooselayout' => 'Suche ein Format aus für $1:',
	'layouts_nolayout' => 'Kein Format',
	'layouts_continue' => 'Weiter',
	'layouts_choosecategory' => 'Suche ein Club aus für $1:',
	'layouts_unknown' => 'Unbekannt',
	'layouts_tagline' => 'Diese Seite wurde mit dem <strong>$1</strong> Layout erstellt.',
);

$messages['pt-br'] = array(
	'layouts_title' => 'Criar uma página',
	'layouts_chooselayout' => 'Escolher um Layout para o $1:',
	'layouts_nolayout' => 'Sem layout',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Escolher uma Categoria para o $1:',
	'layouts_unknown' => 'Desconhecido',
	'layouts_tagline' => 'Esta página foi gerada pelo layout <strong>$1</strong>.',
);
