.TH CHECK_PERMS 8 2001-03-10
.SH NAME
check_perms \- Check permissions of Mailman's files

.SH SYNOPSIS
check_perms [\-f] [\-v] [\-h]

.SH OPTIONS

.TP
\fB\-f\fB
Fix any problems found (when run as root)
.TP
\fB\-v\fB
Be verbose
.PP

.SH DESCRIPTION

With no arguments, just check and report all the files that have bogus
permissions or group ownership. 

.SH AUTHOR
Author of Mailman is the Mailman Cabal, see http://www.list.org/ for
information.  This manpage is written by Tollef Fog Heen
<tfheen@debian.org> for Debian

.SH SEE ALSO
Mailman documentation on http://www.list.org/ and in
/usr/share/doc/mailman.
