.TH LIST_LISTS 8 2006-08-09
.SH NAME
list_lists \- List all Mailman mailing lists on this host

.SH SYNOPSIS
list_lists [options]

.SH OPTIONS

.PP
.TP
\fB\-a\fB, \fB\-\-\fBadvertised\fB
List only those mailing lists that are publically advertised
.TP
\fB\-V\fB \fIdomain\fI, \fB\-\-\fBvirtual-host-overview\fB=\fIdomain\fI
List only those mailing lists that are homed to the given virtual
domain.  This only works if the VIRTUAL_HOST_OVERVIEW variable is
set.
\fB\-b\fB, \fB\-\-\fBbare\fB
Displays only the list name, with no description.
\fB\-h\fB, \fB\-\-help\fB
Print a small help text and exit
.PP

.SH AUTHOR
Author of Mailman is the Mailman Cabal, see http://www.list.org/ for
information.  This manpage is written by Tollef Fog Heen
<tfheen@debian.org> for Debian

.SH SEE ALSO
Mailman documentation on http://www.list.org/ and in
/usr/share/doc/mailman.
