.TH LIST_ADMINS 8 2004-03-24
.SH NAME
list_admins \- List all the owners of a Mailman mailing list.

.SH SYNOPSIS
list_admins [options] listname ...

.SH OPTIONS

.PP
.TP
\fB\-v\fB=\fIvhost\fI, \fB\-\-\fBall\-vhost\fB=\fIvhost\fI
List the owners of all the mailing lists for the given virtual
host.
.TP
\fB\-a\fB, \fB\-\-all\fB
List the owners of all the mailing lists on this system.
.TP
\fB\-h\fB, \fB\-\-help\fB
Print a small help text and exit
.PP

.SH AUTHOR
Author of Mailman is the Mailman Cabal, see http://www.list.org/ for
information.  This manpage is written for Debian by Bernd S. Brentrup
<bsb@debian.org>.

.SH SEE ALSO
Mailman documentation on http://www.list.org/ and in
/usr/share/doc/mailman.
