.TH SYNC_MEMBERS 8 2006-08-09
.SH NAME
sync_members \- Synchronize a mailing list's membership with a flat file.

.SH SYNOPSIS
sync_members [options] -f file listname

.SH DESCRIPTION

This script is useful if you have a Mailman mailing list and a sendmail
:include: style list of addresses (also as is used in Majordomo).  For every
address in the file that does not appear in the mailing list, the address is
added.  For every address in the mailing list that does not appear in the
file, the address is removed.  Other options control what happens when an
address is added or removed.

.SH OPTIONS

.PP
.TP
\fB\-n\fB, \fB\-\-no\-change\fB
Don't actually make the changes.  Instead, print out what would be
done to the list.

.TP
\fB\-w\fB=\fI{ yes | no }\fI, \fB\-\-welcome\-msg\fB=\fI{ yes | no }\fI
Sets whether or not to send the newly added members a welcome message,
overriding whatever the list's `send_welcome_msg' setting is.  With
\fB\-w=yes\fB or \fB\-w\fB, the welcome message is sent.  With
\fB\-w=no\fB, no message is sent.

.TP
\fB\-g\fB=\fI{ yes | no }\fI, \fB\-\-goodbye\-msg\fB=\fI{ yes | no }\fI
Sets whether or not to send the goodbye message to removed members,
overriding whatever the list's `send_goodbye_msg' setting is.  With
\fB\-g=yes\fB or \fB\-g\fB, the goodbye message is sent.  With
\fB\-g=no\fB, no message is sent.

.TP
\fB\-d\fB=\fI{ yes | no }\fI, \fB\-\-digest\fB=\fI{ yes | no }\fI
Selects whether to make newly added members receive messages in
digests.  With \fB\-d=yes\fB or \fB\-d\fB, they become digest members.
With \fB\-d=no\fB (or if no \-d option given) they are added as
regular members.

.TP
\fB\-a\fB=\fI{ yes | no }\fI, \fB\-\-notifyadmin\fB=\fI{ yes | no }\fI
Specifies whether the admin should be notified for each subscription
or unsubscription.  If you're adding a lot of addresses, you
definitely want to turn this off!  With \fB\-a=yes\fB or \fB\-a\fB,
the admin is notified.  With \fB\-a=no\fB, the admin is not notified.
With no \fB\-a\fB option, the default for the list is used.

.TP
\fB\-f\fB=\fIfilename\fI, \fB\-\-file\fB=\fIfilename\fI
This option is required.  It specifies the flat file to synchronize
against.  Email addresses must appear one per line.  If filename is
`\-' then stdin is used.

.TP
\fB\-h\fB, \fB\-\-help\fB
Print a small help text and exit
.PP

listname specifies the list to synchronize.

.SH AUTHOR
Author of Mailman is the Mailman Cabal, see http://www.list.org/ for
information.  This manpage is written by Tollef Fog Heen
<tfheen@debian.org> for Debian

.SH SEE ALSO
Mailman documentation on http://www.list.org/ and in
/usr/share/doc/mailman.
