<?php

require_once 'fundcore_browse.inc';
require_once 'fundcore_list.inc';

/**
 * Implementation of hook_help().
 */
function fundcore_help($section)
{
	switch ($section)
	{
		case 'admin/modules#description':
		     return t('Discloses fundraising data while preserving requested donor privacy.');
	}
}

/**
 * Implementation of hook_perm().
 */
function fundcore_perm()
{
	return array('administer fundcore', 'use fundcore');
}


/**
 * Implementation of hook_menu().
 */
function fundcore_menu($may_cache)
{
	global $user;
	$items = array();

	if ($may_cache)
	{
		$items[] = array(
			'path' => 'fundcore',
			'title' => t('Fundraising C.O.R.E.'),
			'callback' => 'fundcore_page_redirect',
			'access' => user_access('use fundcore'),
		);
		$items[] = array(
			'path' => 'fundcore/list',
			'title' => t('Live contributions'),
			'callback' => 'fundcore_page_main',
			'access' => user_access('use fundcore'),
		);
		$items[] = array(
			'path' => 'fundcore/browse',
			'title' => t('Browse by date'),
			'callback' => 'fundcore_page_browser',
			'access' => user_access('use fundcore'),
			'weight' => 5,
		);
	}
	
	return $items;
}

function fundcore_page_redirect()
{
	drupal_goto('fundcore/list');
}

function fundcore_page_browser()
{
	$year = arg(2);
	$month = arg(3);
	$day = arg(4);

	$output .= _fundcore_currency_summary($year, $month, $day);
	$output .= _fundcore_statistics($year, $month, $day);
	$output .= _fundcore_browse($year, $month, $day);
	
	return $output;	
}

function fundcore_page_main()
{
	$content .= '<p><img src="http://upload.wikimedia.org/fundraising/2006/meter.png" alt="..." style="margin-bottom: 2px;" />';
	$content .= '<br /><a href="http://wikimediafoundation.org/wiki/' . t('Fundraising') . '/"><strong>' . t('Make a Donation') . '</strong></a></p>';
	$content .= '<p><strong>Q:</strong> Why did the meter jump up over $200,000?';
	$content .= '<br /><strong>A:</strong> We added the anonymous matching donation.</p>';

	$content .= '<p><strong>Coming soon:</strong> RSS feeds, maybe an IRC bot, and ';
	$content .= '<a href="http://meta.wikimedia.org/wiki/Fundraising_C.O.R.E.">more translations</a>.</p>';
	$content .= _fundcore_filter();
	$content .= _fundcore_results();
	return $content;
}
