<?
# DO NOT EDIT THIS FILE!
# To customize your installation, edit "WikiLocalSettings.php".

#$wgServer           = "http://127.0.0.1";
$wgServer           = "http://" . getenv( "SERVER_NAME" );
$wgStyleSheetPath   = "$wgServer/style";
$wgScript           = "/wiki/wiki.phtml";
$wgArticlePath      = "$wgServer$wgScript?title=$1";
$wgUploadPath       = "/upload";
$wgUploadDirectory	= "/var/www/html/upload";

# MySQL settings
#
$wgDBserver         = "127.0.0.1";
$wgDBname           = "wikidb";
$wgDBuser           = "wikiuser";
$wgDBpassword       = "xxx";
$wgDBconnection     = "";

$wgReadOnly = false;
$wgDebugComments = false;
$wgCachePages = false;

$wgLanguageCode     = "en";
$wgDocType          = "-//W3C//DTD HTML 4.01 Transitional//EN";
$wgCookieExpiration = 2592000;

?>
