/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.mediawiki.android.client;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int mediawiki=0x7f020001;
    }
    public static final class id {
        public static final int MainPage_EditText=0x7f050002;
        public static final int MainPage_image=0x7f050001;
        public static final int MainPage_parent=0x7f050000;
        public static final int SearchPage=0x7f050003;
        public static final int SearchResultRow=0x7f050005;
        public static final int ViewPage=0x7f050004;
        public static final int ViewPage_root=0x7f050006;
        public static final int ViewPage_text=0x7f050007;
    }
    public static final class layout {
        public static final int config=0x7f030000;
        public static final int main=0x7f030001;
        public static final int search_result_row=0x7f030002;
        public static final int view_page=0x7f030003;
    }
    public static final class string {
        public static final int app_authors=0x7f040002;
        public static final int app_license=0x7f040003;
        /**  GLOBAL THINGS 
         */
        public static final int app_name=0x7f040000;
        public static final int app_version=0x7f040001;
        public static final int fetch_data=0x7f040004;
        public static final int intent_config=0x7f040010;
        /**  INTENTS FOR MANIFEST 
         */
        public static final int intent_edit=0x7f04000c;
        public static final int intent_main=0x7f04000d;
        public static final int intent_search=0x7f04000f;
        public static final int intent_view=0x7f04000e;
        public static final int menu_about=0x7f040006;
        public static final int menu_categories=0x7f04000a;
        public static final int menu_config=0x7f040007;
        /**  MAIN MENU 
         */
        public static final int menu_home=0x7f040005;
        public static final int menu_langlinks=0x7f04000b;
        public static final int menu_pagelinks=0x7f040009;
        public static final int menu_search=0x7f040008;
        public static final int pref_cachetime=0x7f040014;
        public static final int pref_cachetime_summary=0x7f040015;
        public static final int pref_usecache=0x7f040012;
        public static final int pref_usecache_summary=0x7f040013;
        /**  PREFERENCES 
         */
        public static final int prefcat_caching=0x7f040011;
        public static final int prefcat_wikis=0x7f040016;
    }
}
