<?php
header("Content-Type: text/html; charset=UTF-8");

require_once('/etc/logwood-fe/lw-support.php');
require_once('/etc/logwood-fe.conf');
$site = false;
if (isset($_REQUEST['site']))
	$site = $_REQUEST['site'];

$db = new lw_db($site);

$dbh = mysql_connect($server, $username, $password);
$site = mysql_real_escape_string($_REQUEST['site'], $dbh);

mysql_select_db($database, $dbh);
?>
<html>
<head>
<title>Access statistics</title>
<link rel="stylesheet" href="<?php echo $htmlbase?>/logwood.css" />
</head>
<body>
<div id="header">

<div class='selectsite'>
<form action='' method='get'>

Site: 
<select name="site">
<?php
$q = mysql_query("SELECT si_name FROM sites ORDER BY si_name ASC", $dbh);
while ($o = mysql_fetch_assoc($q)) {
	$opt = $o["si_name"];
	$selected = ($opt == $site) ? " selected='selected'" : "";
	echo "<option value='$opt'$selected>$opt</option>\n";
}
mysql_free_result($q);
?>
</select>

<input type='submit' value='Go' />
</form>
</div>
	<h1>Statistics<?php if ($site != '') { ?> 
		for <strong><?php echo htmlspecialchars($site)?></strong><?php } ?>
	</h1>
</div> 

<?php
if ($site !== false && $site != '') {

$top_urls = mysql_query("
	SELECT si_name, ur_path,tu_count FROM sites, topurls, url_id 
	WHERE tu_site=si_id and si_name='$site' and tu_url=ur_id 
	ORDER BY tu_count DESC LIMIT 100;
	");

?>

<h2>Most popular URLs</h2>
<div class='titlesub'>
<?php 
$fdate = date('Y-m');
$fname = "/archive/$site/$fdate/$fdate.$site.all_urls.txt";
$st = @stat($lwbase.$fname);
?>
<a href="<?php echo "$htmlbase$fname"?>">View all URLs</a> (<?php echo $st["size"]?> bytes)
</div>

<table><tr><th>#</th><th>Views</th><th>URL</th></tr>
<?php
$i = 1;
while ($url = mysql_fetch_assoc($top_urls)) {
	$purl = htmlspecialchars("http://" . $url["si_name"] . "/" . urldecode($url["ur_path"]));
	$lurl = htmlspecialchars("http://" . $url["si_name"] . "/" . $url["ur_path"]);
	$count = $url["tu_count"];
	echo "<tr><td>$i</td><td>$count</td><td><a href=\"$lurl\">$purl</a></td></tr>\n";
	++$i;
}
mysql_free_result($top_urls);
?>
</table>

<h2>Most active hours</h2>

<div class='image'>
<img src="/logwood-hour-graph.php?site=<?php echo htmlspecialchars(urlencode($site))?>" />
</div>

<table>
<?php
$hours = $db->edits_by_hour();

echo "<tr><th>Hour</th>";
for ($i = 0; $i < 12; ++$i) echo "<th>$i</th>";
echo "</tr>\n";
echo "<tr><th>Visits</th>";
for ($i = 0; $i < 12; ++$i) echo "<td>{$hours[$i]}</td>";
echo "</tr>\n";

echo "<tr><th>Hour</th>";
for ($i = 12; $i < 24; ++$i) echo "<th>$i</th>";
echo "</tr>\n";
echo "<tr><th>Visits</th>";
for ($i = 12; $i < 24; ++$i) echo "<td>{$hours[$i]}</td>";
echo "</tr>\n";

?>
</table>

<h2>Most active days</h2>

<div class='image'>
<img src="/logwood-wday-graph.php?site=<?php echo htmlspecialchars(urlencode($site))?>" />
</div>
<table>
<tr><th></th><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th></tr>
<tr><th>Hits</th>
<?php
$wdays = $db->edits_by_wday();

foreach ($wdays as $day => $count)
	echo "<td>$count</td>\n";

?>
</tr></table>

<h2>Most common referers</h2>

<table>
<tr><th>#</th><th>Count</th><th>Referer</th></tr>
<?php
$refers = mysql_query("
	SELECT ref_url, ref_grouped, tr_count
	FROM sites, ref_ids, toprefs
	WHERE si_name='$site' AND ref_site=si_id AND tr_ref=ref_id
	ORDER BY tr_count DESC LIMIT 50
	");
$i = 1;
while ($refer = mysql_fetch_assoc($refers)) {
	$purl = htmlspecialchars(urldecode(urldecode($refer["ref_url"])));
	$lurl = htmlspecialchars(urldecode($refer["ref_url"]));
	$group = $refer["ref_grouped"] ? " class='grouped'" : "";
	$count = $refer["tr_count"];
	echo "<tr><td$group>$i</td><td$group>$count</td><td$group><a rel='nofollow' href=\"$lurl\">$purl</a></td></tr>\n";
	$i++;
}
mysql_free_result($refers);
?>
</table>

<h2>Most popular User-Agents</h2>

<table>
<tr><th>#</th><th>Count</th><th>Agent</th></tr>
<?php
$agents = mysql_query("
	SELECT ag_name, ag_grouped, ta_count
	FROM sites, agent_ids, topagents
	WHERE si_name='$site' AND ag_site=si_id AND ta_agent=ag_id
	ORDER BY ta_count DESC LIMIT 50
	");
$i = 1;
while ($agent = mysql_fetch_assoc($agents)) {
	$pagent = htmlspecialchars(urldecode($agent["ag_name"]));
	$count = $agent["ta_count"];
	$group = $agent["ag_grouped"] ? " class='grouped'" : "";
	echo "<tr><td$group>$i</td><td$group>$count</td><td$group>$pagent</td></tr>\n";
	$i++;
}
mysql_free_result($agents);
?>
</table>

<?php
}
?>

<hr>
<p id='motif'>Statistics generated by <a href="mailto:keturner@livejournal.com">Logwood</a>
<?php echo $db->version()?>; PHP <?php echo phpversion() ?>, 
MySQL <?php echo $db->mysql_version() ?>.</p>
</body>
</html>
