HTMLDIR=	/var/www/html/logwood/
LWDIR=		/etc/logwood-fe

FILES=		logwood-wday-graph.php logwood-hour-graph.php logwood.php	\
		logwood.css ../stat/Headbg.jpg
install:
	cp $(FILES) $(HTMLDIR)
	cp lw-support.php $(LWDIR)

