.Dd April 11, 2005
.Dt TRICKLE 1
.Os Wikimedia
.Sh NAME
.Nm trickle
.Nd copy one directory to another directory or a tar file, slowly
.Sh SYNOPSIS
.Nm
.Op Fl Fpt | uPr
.Op Fl q
.Op Fl x Ar filename
.Op Fl s Ar blocksize
.Op Fl b Ar blocksleep
.Op Fl f Ar filesleep
.Op Fl T Ar path
.Op Fl z Ar program
.Ar source
.Ar [host:]destination
.Sh DESCRIPTION
The
.Nm
utility copies one directory to another directory, or creates a
.Xr tar 1
file from it, slowly.  Specifically, it sleeps for
.Ar blocksleep
microseconds after copying each 
.Ar blocksize
bytes, and sleeps for
.Ar filesleep
seconds after copying each file or directory.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl u
Only copy files which don't exist in the destination, or have a newer modification
time.  The
.Fl u
option may not be specified at the same time as the
.Fl t
option.
.It Fl t
Instead of copying to a directory tree, output a
.Xr tar 1
file named
.Ar destination ,
or output to stdout if
.Ar destination
is "-".  The
.Fl t 
option may not be specified at the same time as the
.Fl u
option.
.It Fl s Ar blocksize
Copy the file in
.Ar blocksize
increments.
.It Fl b Ar blocksleep
Sleep for
.Ar blocksleep
microseconds after copying each block.
.It Fl f Ar filesleep
Sleep for
.Ar filesleep
microseconds after copying each file.
.It Fl F 
If
.Ar dest
is a file and already exists, overwrite it without prompting.
.It Fl q
Be less verbose.
.It Fl p
Write pax(1) extended headers when a filename is too long to be
represented by tar.  When this occurs, the file will still be
extractable by tar, but its filename will be truncated, and a
dummy file called "@PAX.HEADER" will be created.  The pax(1)
format is compatible with GNU tar.
.It Fl x Ar name
Don't copy directories called
.Ar name .
.It Fl P
Preserve ownership and file permissions of copied files.
.It Fl z Ar path
Use
.Ar path
instead of
.Xr rsh 1 .
.It Fl r
Copy files to a remote host using
.Xr rsh 1
.It Fl T Ar path
Use
.Ar path
as the
.Nm
program on the remote host.
.El
.Sh NOTES
The POSIX.1
.Xr tar 1
file format is limited to 255 bytes of pathname; 155 bytes for the directory name,
and 100 bytes for the filename.  Path or filenames longer than this will be truncated.
.Sh AUTHOR
Kate Turner <keturner@livejournal.com>.
.Sh SEE ALSO
.Xr tar 1 ,
.Xr pax 1 ,
.Xr rsh 1 .
.Pp
.St -susv2
