#! /bin/sh

case "$1" in
	remove)
		;;
	purge)
		if [ -e /usr/share/debconf/confmodule ]; then
			# Source debconf library.
			. /usr/share/debconf/confmodule
			# Remove my changes to the db.
			db_purge
		fi
		echo "Purging startup links .."
		rm -f /etc/init.d/squid
		update-rc.d squid remove > /dev/null
		echo "Purging logfiles .."
		rm -rf /var/log/squid
        	if [ -f /etc/squid/squid.conf ]; then
			echo "Removing the config-file .."
			rm -f /etc/squid/squid.conf
		fi
		if [ -f /etc/default/squid ]; then
			rm -f /etc/default/squid
		fi

		#
        	# We do not remove /var/spool/squid because that might
        	# take a lot of time. Most of the time it is on a seperate
        	# disk anyway and it is faster to do a mkfs on it..
        	#
        	echo "Remove the proxy cache in /var/spool/squid yourself!"
		;;
	failed-upgrade)
		if (dpkg --compare-versions "$2" le '2.5.4-4' && [ -e /etc/squid/conffile-moved ])
		then
			mv /etc/squid/squid.conf /etc/squid.conf
			rm /etc/squid/conffile-moved
		fi
		;;
	upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

