.TH SQUID-CGI 8 "Januari 1998" "Squid CGI Interface" "Debian Linux"
.SH NAME
squid-cgi \- CGI interface to squid
.SH SYNOPSIS
.B /usr/lib/cgi-bin/squid-cgi
.SH DESCRIPTION
.B Squid-cgi
is a CGI program that can be used as a WWW-based frontend to the
squid object cache. It should be run as a CGI script through your
WWW server.
.PP
.SH "SEE ALSO"
.BR squid (8)
