Document: wikimedia-base
Title: Debian wikimedia-base Manual
Author: <insert document author here>
Abstract: This manual describes what wikimedia-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wikimedia-base/wikimedia-base.sgml.gz

Format: postscript
Files: /usr/share/doc/wikimedia-base/wikimedia-base.ps.gz

Format: text
Files: /usr/share/doc/wikimedia-base/wikimedia-base.text.gz

Format: HTML
Index: /usr/share/doc/wikimedia-base/html/index.html
Files: /usr/share/doc/wikimedia-base/html/*.html

  
