#!/bin/sh

set -e

# Only act on loopback interface actions
[ "$IFACE" = "lo" ] || exit 0

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

. /etc/default/wikimedia-lvs-realserver

# Compile a list of LVS service IPs currently bound to lo
LVS_SERVICE_IPS=$(ip addr show label "lo:LVS" | awk '{ print $2 }')

# Delete the service IPs from the loopback interface
for SIP in $LVS_SERVICE_IPS
do
	ip addr del $SIP label "lo:LVS" dev lo
done
