#!/bin/bash

if [ "$1" = configure ]; then
	if ! grep -q wikimedia-raid-utils /etc/sudoers;then
		chmod 640 /etc/sudoers
		cat > /etc/sudoers <<end

## Added by wikimedia-raid-utils
nagios ALL=NOPASSWD: /usr/bin/check-raid.py ""
## End wikimedia-raid-utils
end
		chmod 440 /etc/sudoers
	fi
fi

