#!/bin/sh
#
# This is an aggregated version of the scripts called by /home/w/bin/sync-common,
# not depending on NFS /home.

set -e
umask 002

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

# Set ownership
[ -d /usr/local/apache/common-local/php-1.5 ] || mkdir -p /usr/local/apache/common-local/php-1.5
find /usr/local/apache/common/php-1.5 -group wikidev -not -perm -020 -perm -200 -exec chmod g+w '{}' ';'

# Compile texvc
echo -n Compiling texvc... 
[ -d /var/tmp/texvc ] || mkdir /var/tmp/texvc
rsync -r --exclude=.svn/ 10.0.5.8::common/php-1.5/math/ /var/tmp/texvc
cd /var/tmp/texvc
make -f Makefile texvc >/dev/null 2>/dev/null && echo ok || echo failed
sudo /usr/sbin/install-common
rm -rf /var/tmp/texvc

# rsync common
echo -n Copying to `hostname -s`...
rsync -a --delete '--exclude=**/.svn/lock' 10.0.5.8::common/ /usr/local/apache/common-local
echo Done.
