#!/usr/bin/python

import getopt
import sys
import time

def rate(nbytes, interval):
	if interval == 0.0:
		rate = 0.0
	else:
		rate = (float(nbytes) / 1048576.0) / interval
	return "%0.3f MB/sec" % rate

def report(nbytes, interval, totalBytes, longTerm):
	sys.stderr.write("%s now, %s average\n" % \
		(rate(nbytes, interval), rate(totalBytes, longTerm)))

bufferSize = 8192 # bytes to read at a time
reportingInterval = 1.0 # reporting interval

(options, remainder) = getopt.getopt(sys.argv[1:], "b:")
for (opt, val) in options:
	if opt == "-b":
		bufferSize = int(val)
if remainder:
	reportingInterval = float(remainder[0])


bytesRead = 0L
bytesTotal = 0L
startTime = time.time()
lastTime = startTime
now = startTime

buffer = sys.stdin.read(bufferSize)
while buffer:
	sys.stdout.write(buffer)
	bytesRead += len(buffer)
	bytesTotal += len(buffer)
	now = time.time()
	if now - lastTime >= reportingInterval:
		report(bytesRead, now - lastTime, bytesTotal, now - startTime)
		lastTime = now
		bytesRead = 0L
	buffer = sys.stdin.read(bufferSize)

report(bytesRead, now - lastTime, bytesTotal, now - startTime)
