#!/bin/bash

for srv in ms1; do
	echo $srv
	rsync --rsh=ssh -cr /home/wikipedia/upload-scripts/ root@$srv:/export/upload/sync-from-home
done

for srv in ms4; do
	echo $srv
	rsync --rsh=ssh -cr /home/wikipedia/upload-scripts/ root@$srv:/export/thumbs/sync-from-home
done
