#!/bin/sh

config ()
{
	echo "$3"
	echo -n "$1"
	if [ -e ./configData/$1 ]; then
		DEFAULT=$(cat ./configData/$1)
	else
		DEFAULT=$2
	fi
	echo -n " [$DEFAULT]: "
	read -r VAL
	if [ "$VAL" ]; then
		if [ $CYGPATH ]; then
			VAL=`cygpath -w "$VAL"`
		fi
		echo "$VAL" > ./configData/$1
	else
		if [ ! -e ./configData/$1 ]; then
			VAL=$2
			if [ $CYGPATH ]; then
				VAL=`cygpath -w "$VAL"`
			fi
			echo "$VAL" > ./configData/$1
		fi
	fi
	echo
}

CYGPATH=
if [ -x /usr/bin/cygpath ]; then
	echo "cygpath exists, using it to convert paths."
	CYGPATH=1
fi

config mysqlroot /usr "The root where the MySQL installation can be found. %mysqlroot%/bin/mysqld should be valid."
config phproot /usr/bin/ "The root where the PHP binaries can be found. %phproot%php and %phproot%php-cgi should be valid. Include the trailing slash."
config phpini "$PWD" "The directory to find the php.ini configuration file to give to php-cgi for configuration info. Defaults to the SDK's diretory where one will be created with ./server config."
config phpext "`cat configData/phproot`ext/" "The directory to find PHP extensions, defaults to the ext/ directory under the phproot. Include the trailing slash."
config docroot "$PWD/htdocs/" "The web root for the wiki setups. Normally the htdocs subdirectory. Include the trailing slash."
config logfile "`cat configData/docroot`server.log" "The logfile for the webserver to log to. Normally inside the htdocs so SVN doesn't catch it."
config port    8000 "The port on which to run the webserver."