#!/bin/sh

case "$1" in
	webdocs)
		echo "Creating phpinfo.php"
		echo "<?php phpinfo();" > "`cat configData/docroot`phpinfo.php"
		;;
	phpmyadmin)
		cd "`cat configData/docroot`"
		if [ -e phpMyAdmin ]; then
			echo "Updating copy of phpMyAdmin"
			cd phpMyAdmin
			svn update
		else
			echo "Downloading stable copy of phpMyAdmin"
			svn checkout https://phpmyadmin.svn.sourceforge.net/svnroot/phpmyadmin/tags/STABLE/phpMyAdmin phpMyAdmin
		fi
		;;
	*)
		echo "Usage: $0 webdocs    - Generate the helper documents into the webroot."
		echo "Usage: $0 phpmyadmin - Download, or update, a copy of phpMyAdmin for administration of the databases."
		;;
esac

exit 0