<?
# THIS IS THE MAIN FILE OF THE PHP WIKIPEDIA SCRIPT

$THESCRIPT = "wiki.phtml" ; # The name of the script. The $PHP_SELF variable doesn't work with Netscape

# Includes the necessary parts
#include_once ( "./specialPages.php" ) ;
include_once ( "./basicFunctions.php" ) ;
include_once ( "./databaseFunctions.php" ) ;
include_once ( "./wikiTitle.php" ) ;
include_once ( "./wikiPage.php" ) ;
include_once ( "./wikiUser.php" ) ;

# Main program
	global $action , $title , $pageTitle ;
	global $user , $search , $expiration ;
	global $THESCRIPT ;
	$expiration = time()+315360000 ; # Cookies set will expire in ten years from now
	$pageTitle = "" ;

	# Verifying the current user. Logged in? Password in a cookie?
	$user = new WikiUser ;
	$user->scanCookies () ;

	# Default settings
	if ( $action == "" ) $action = "view" ;
	if ( $title == "" ) $title = "HomePage" ;
	
	$theTitle = new wikiTitle ;
	$theTitle->title = urldecode ( $title ) ;
	$theTitle->makeSecureTitle () ;
	$title = $theTitle->secureTitle ;

	$action = strtolower ( trim ( $action ) ) ;
	$title = urldecode ( $title ) ;

	# Do what is asked
	if ( isset ( $search ) ) {
		$out = doSearch () ;
		unset ( $search ) ;
	} else  if ( $action == "watch" ) {
		global $mode ;
		$out = watch ( $title , $mode ) ;
	} else if ( $action == "view" ) $out = view ( $title ) ;
	else if ( $action == "edit" ) $out = doEdit ( $title ) ;
	else if ( $action == "history" ) {
		include_once ( "./specialPages.php" ) ;
		$out = doHistory ( $title ) ;
	} else $out = error ( "No such action \"$action\"" ) ;

	# Cleaning up, setting <title>, etc.
	global $bodyOptions , $headerScript ;
	$pageTitle = "Wikipedia : ".str_replace ( "_" , " " , $pageTitle ) ;
	$bodyOptions .= $user->options["background"] ;
	$bodyOptions .= $user->options["text"] ;
	$head = "<HTML><HEAD><TITLE>$pageTitle</TITLE> $headerScript </HEAD><BODY $bodyOptions>\n" ;
	$tail = "</BODY></HTML>" ;

	# Adjusting link style
	$linkStyle = "style=\"color:blue\"" ;
	if ( $user->options["underlineLinks"] == "no" ) $linkStyle = "style=\"color:blue;text-decoration:none\"" ;
	if ( $user->options["forceLinks"] != "" ) $linkStyle = $user->options["forceLinks"] ;
	$out = str_replace ( "<a href=" , "<a $linkStyle href=" , $out ) ;
	$out = str_replace ( "&lt;a style=\"color:blue\"" , "&lt;a " , $out ) ; # Correcting weird replacement above

	global $append; # For testing. Usually, $append is empty
	print $head.$out.$tail.$append ; # FINALLY!!!!
?>