<?
# DO NOT EDIT THIS FILE!
# To customize your installation, edit "WikiLocalSettings.php".

$wgServer           = "http://" . getenv( "SERVER_NAME" );
$wgScriptPath	    = "/wiki";
$wgScript           = "{$wgScriptPath}/wiki.phtml";
$wgStyleSheetPath   = "{$wgServer}/style";
$wgArticlePath      = "{$wgServer}{$wgScript}?title=$1";
$wgUploadPath       = "{$wgServer}/upload";
$wgLogo				= "{$wgUploadPath}/wiki.png";
$wgUploadDirectory	= "/var/www/html/upload";

# MySQL settings
#
$wgDBserver         = "127.0.0.1";
$wgDBname           = "wikidb";
$wgDBuser           = "wikiuser";
$wgDBpassword       = "userpwd";
$wgDBconnection     = "";

$wgReadOnly = false;
$wgDebugComments = false;
$wgCachePages = false;

$wgLanguageCode     = "en";
$wgInputEncoding	= "ISO-8851-1";
$wgOutputEncoding	= "ISO-8851-1";

$wgDocType          = "-//W3C//DTD HTML 4.01 Transitional//EN";
$wgCookieExpiration = 2592000;

?>
