<?
# Main wiki script
#
session_start();
session_register( "wsUserID" );
session_register( "wsUserName" );
session_register( "wsUserPassword" );

$wgRequestTime = microtime();
include_once( "Setup.php" );

# Query string fields
#
global $action, $title, $search, $target, $printable;
global $target, $returnto;

wfStripTextFields(); # Clean up PHP mess

$action = strtolower( trim( $action ) );
if ( "" == $action ) { $action = "view"; }
if ( "yes" == $printable ) { $wgOut->setPrintable(); }

if ( "" == $title ) {
	$wgTitle = Title::newFromText( wfMsg( "mainpage" ) );
} else {
	$wgTitle = Title::newFromURL( $title );
}
if ( -1 == $wgTitle->getNamespace() ) {
	wfSpecialPage();
} else if ( "" != $search ) { wfSearch( $search ); }
else {
	$wgArticle = new Article();

	if ( "view" == $action ) { $wgArticle->view(); }
	else if ( "edit" == $action ) { $wgArticle->edit(); }
	else if ( "print" == $action ) { $wgArticle->view(); }
	else if ( "watch" == $action ) { $wgArticle->watch(); }
	else if ( "history" == $action ) { $wgArticle->history(); }
	else { $wgOut->errorpage( "nosuchaction", "nosuchactiontext" ); }
}

$wgOut->output();

foreach ( $wgDeferredUpdateList as $up ) { $up->doUpdate(); }

?>
