.TH SLAYERD 8 "April 19, 2007"
.SH NAME
slayerd \- trim errant user processes
.SH SYNOPSIS
.B slayerd
[-vhf]
.SH DESCRIPTION
.B slayerd
is a daemon which monitors the system for users using too much memory.
If the size of all of a user's processes exceed the maximum limit, slayerd
will kill the user's processes in decreasing order of size, until the
user's memory use drops below the threshold.
.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show program version.
.SH CONFIGURATION
.B slayerd
reads its configuration from \fI/etc/slayerd/slayerd.conf\fP.  The following
options may be set in this file:
.TP
.B \fBlimit\fP \fInum\fP 
(required)
The maximum amount of memory (in megabytes) that a user may use before their
processes are killed.
.TP
.B \fBthresh\fP \fInum\fP
(required)
When a user exceeds their memory limit, their processes will be killed until
they are using less than this amount of memory (in megabytes).
.TP
.B \fBdelay\fP \fIsecs\fP
(required)
The time in seconds to sleep between each check.
.TP
.B \fBexempt\fP \fIuser\fP
A user who will be exempt from monitoring.  \fIroot\fP is always exempt.  This
option may be specified multiple times.
.TP
.B \fBminuid\fP \fIuid\fP
All users whose user id is less than \fIuid\fP will be exempt.
.TP
.B \fBsendmail\fP \fIcommand\fP
The path to the sendmail command that will be used to send mail.
.TP
.B \fBpidfile\fP \fIpath\fP
Pathname to write pid file to on startup.

.SH MAIL MESSAGE
When a user's processes are killed,
.B slayerd
will send them a mail explaining what happened.  The contents of this message
are in \fI/etc/slayerd/mailmessage\fP.  The following substition variables
may be used in the message:
.TP
.B \fB%hostname%\fP
The hostname of the machine.
.TP
.B \fB%user%\fP
The username of the user whose processes were killed.
.TP
.B \fB%limit%\fP
The value of the \fIlimit\fP option in the configuration.
.TP
.B \fB%thresh%\fP
The value of the \fIthresh\fP option in the configuration.
.TP
.B \fB%current%\fP
The amount of memory used by the user after their processes were killed.
.TP
.B \fB%processes%\fP
The list of processes killed, one per line.

.SH AUTHOR
slayerd was written by River Tarnell <river@attenuate.org>.
