# Set build options here.
#
# Compiler
cc = 'gcc'
cxx = 'g++'

#cflags = '-O2 -g -W -Wall'
cflags = '-g -W -Wall'
cppflags = ''

# Where things are installed to.
prefix = ARGUMENTS.get('prefix', '/opt/servmon')

# Don't change anything below here.
####################################
import os

srcs = Split(	'servmon.cxx csmplex.cxx smthr.cxx smnet.cxx smutl.cxx smcfg.cxx smirc.cxx '
		'smauth.cxx smtmr.cxx smmon.cxx')
env = Environment(CPPFLAGS = cppflags + ' -DPFX="\\"' + prefix + '\\""',
		CCFLAGS = cflags,
		CC = cc,
		CXX = cxx,
		CPPPATH = 'include')

env.Program ('servmon', srcs, LIBS = ['pthread', 'boost_thread', 'netsnmp', 'ssl'])
env.Program ('initconf', ['initconf.cxx', 'smcfg.cxx', 'smauth.cxx'], LIBS = ['pthread', 'boost_thread'])
env.Alias('install', prefix)
