<?php

function fundcore_frontpage_panels_layouts() {
  $items['fundcore_frontpage'] = array(
    'module' => 'fundcore_frontpage_panel',
    'title' => t('Fundraising CORE Frontpage'),
    'icon' => drupal_get_path('module', 'fundcore_frontpage') . '/fundcore_frontpage_panel_layout.png',
    'theme' => 'fundcore_frontpage_panel',
    'css' => 'fundcore_frontpage_panel_layout.css',
    'content areas' => array(
      'left' => t('Left side'),
      'right' => t('Right side'),
    ),
  );

  return $items;
}

function theme_fundcore_frontpage_panel($id, $content) {
  $content = '<table border="0" cellspacing="0" cellpadding="0"><tr>
					<td width="463" valign="top">' . $content['left'] . '</td>
					<td width="38"></td><!-- Spacer middle of the page -->
					<td width="321" valign="top">' . $content['right'] . '</td>
				</tr></table>';
  return $content;
}

function _fundcore_frontpage_render($file, $variables = array()) {
  extract($variables, EXTR_SKIP);
  ob_start();
  include $file;
  $contents = ob_get_contents();
  ob_end_clean();
  return $contents;
}

function fundcore_frontpage_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['donatebox'] = array(
      'info' => t('FundCORE Frontpage: Donation box'),
    );
    $blocks['otherbox'] = array(
      'info' => t('FundCORE Frontpage: Other box'),
    );
    $blocks['storybox'] = array(
      'info' => t('FundCORE Frontpage: Story box'),
    );
    $blocks['videobox'] = array(
      'info' => t('FundCORE Frontpage: Video box'),
    );
    $blocks['whatweneedbox'] = array(
      'info' => t('FundCORE Frontpage: What We Need box'),
    );
    $blocks['lastline'] = array(
      'info' => t('FundCORE Frontpage: Last line text'),
    );
    return $blocks;
  }
  else if ($op == 'view') {
    $block = array(
      'content' => _fundcore_frontpage_render('content/' . $delta . '.inc'),
    );
    return $block;
  }
}
