<?php

function fundcore_frontpage_menu($may_cache) {
  $items = array();
  
  if ($may_cache) {
    $items[] = array(
      'path' => 'fundcore_frontpage',
      'type' => MENU_CALLBACK,
      'access' => TRUE,
      'callback' => 'fundcore_frontpage_page',
    );
  }
  
  return $items;
}

function fundcore_frontpage_page() {
  //drupal_set_title('Contribute');

  $content = _fundcore_frontpage_render('fundcore_frontpage.content.inc');
  
  return $content;
}

function _fundcore_frontpage_render($file, $variables = array()) {
  extract($variables, EXTR_SKIP);
  ob_start();
  include $file;
  $contents = ob_get_contents();
  ob_end_clean();
  return $contents;
}

function fundcore_frontpage_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Fundraising footer'),
      'weight' => 0,
      'enabled' => 1,
      'region' => 'last_line'
    );
    return $blocks;
  }
  else if ($op == 'view') {
    $block = array(
      'content' => _fundcore_frontpage_render('fundcore_frontpage.block.inc'),
    );
    return $block;
  }
}
