#!/bin/sh

set -e

CONFIGFILE=/etc/default/wikimedia-lvs-realserver
DEFAULT_LVS_SERVICE_IPS="10.0.5.3"

. /usr/share/debconf/confmodule
db_version 2.0

db_get wikimedia-lvs-realserver/service_ips
if [ -z "$RET" ]
then
	db_fget wikimedia-lvs-realserver/service_ips seen
	if [ "$RET" = "false" ]
	then
		# Empty value in preseed db, and seen set to false.
		# Set a default
		db_set wikimedia-lvs-realserver/service_ips $DEFAULT_LVS_SERVICE_IPS
	fi
fi

# A preexisting configuration file is authoritative
if [ -f $CONFIGFILE ]
then
	. $CONFIGFILE

	[ -n "$LVS_SERVICE_IPS" ] && db_set wikimedia-lvs-realserver/service_ips "$LVS_SERVICE_IPS"
fi

db_input high wikimedia-lvs-realserver/service_ips || true
db_go || true
