Document: wikimedia-lvs-realserver
Title: Debian wikimedia-lvs-realserver Manual
Author: <insert document author here>
Abstract: This manual describes what wikimedia-lvs-realserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wikimedia-lvs-realserver/wikimedia-lvs-realserver.sgml.gz

Format: postscript
Files: /usr/share/doc/wikimedia-lvs-realserver/wikimedia-lvs-realserver.ps.gz

Format: text
Files: /usr/share/doc/wikimedia-lvs-realserver/wikimedia-lvs-realserver.text.gz

Format: HTML
Index: /usr/share/doc/wikimedia-lvs-realserver/html/index.html
Files: /usr/share/doc/wikimedia-lvs-realserver/html/*.html

  
