#!/bin/bash

if [ "X$2" == X ]; then
	echo "Usage: compress-html <language> <edition>"
	exit
fi

. `dirname $0`/config.sh

lang=$1
edition=$2
site=wikipedia

sitebase=$base/new/$site
dest=$base/downloads/$edition/$lang
p7zip=$base/scripts/7za-readdir-hack

mkdir -p $dest

echo Finding files...
cd $sitebase
find $lang -name \*.html > $dest/html.lst

find $lang/skins $lang/raw $lang/misc -type f > $dest/skins.lst
echo $lang/dumpHTML.version >> $dest/skins.lst

find $lang/images -not -type d > $dest/images.lst

echo Creating HTML archive...
rm -f $dest/wikipedia-$lang-html.7z

# Set chunk size to 8MB for faster random access
$p7zip -l -ms8m a $dest/wikipedia-$lang-html.7z @$dest/html.lst @$dest/skins.lst

fileCount=`wc -l $base/downloads/$edition/$lang/html.lst | awk '{print $1}'` 
if [ $fileCount -gt 2000000 ]; then
	echo "Creating split archives"
	$base/scripts/compress-volumes "$lang" "$edition"
fi

