#!/bin/bash

if [ "X$2" == "X" ];then
	echo "Usage: finish <lang> <edition>"
	exit
fi
bindir=/mnt/static/scripts
lang=$1
edition=$2
site=wikipedia

if [ ! -d /mnt/static/$site/$lang-new ]; then
	echo "Already compressed $lang"
	exit
fi
if [ ! -e /mnt/static/$site/$lang-new/index.html ]; then
	echo "$lang-new directory is broken, missing index.html, skipping."
	exit
fi
	
if [ -d /mnt/static/$site/$lang ];then
	if [ -d /mnt/static/$site/$lang-old ];then
		rm -rf /mnt/static/$site/$lang-old
	fi
	mv /mnt/static/$site/$lang /mnt/static/$site/$lang-old
fi
mv /mnt/static/$site/$lang-new /mnt/static/$site/$lang

echo "$lang: Compressing HTML..."
$bindir/compress-html $lang $edition 2>&1 >/dev/null
#echo "$lang: Making image tarball..."
#ssh albert tar -C /mnt/static -cf /a/upload_snapshot/$edition/downloads/wikipedia-$lang-images.tar -h $lang/upload
#ln -sf /mnt/upload_snapshot/$edition/downloads/wikipedia-$lang-images.tar /mnt/static/downloads/$edition/$lang/wikipedia-$lang-images.tar
echo "$lang: Done."
