<?php

require_once 'fundcore_browse.inc';
require_once 'fundcore_list.inc';

/**
 * Implementation of hook_help().
 */
function fundcore_help($section)
{
	switch ($section)
	{
		case 'admin/modules#description':
		     return t('Discloses fundraising data while preserving requested donor privacy.');
	}
}

/**
 * Implementation of hook_perm().
 */
function fundcore_perm()
{
	return array('administer fundcore', 'use fundcore');
}


/**
 * Implementation of hook_menu().
 */
function fundcore_menu($may_cache)
{
	global $user;
	$items = array();

	if ($may_cache)
	{
		$items[] = array(
			'path' => 'fundcore',
			'title' => t('Fundraising C.O.R.E.'),
			'callback' => 'fundcore_page_redirect',
			'access' => user_access('use fundcore'),
		);
		$items[] = array(
			'path' => 'fundcore/list',
			'title' => t('Live contributions'),
			'callback' => 'fundcore_page_main',
			'access' => user_access('use fundcore'),
		);
		$items[] = array(
			'path' => 'fundcore/browse',
			'title' => t('Browse by date'),
			'callback' => 'fundcore_page_browser',
			'access' => user_access('use fundcore'),
			'weight' => 5,
		);
	}
	
	return $items;
}

function fundcore_page_redirect()
{
	drupal_goto('fundcore/list');
}

function fundcore_page_browser($year = NULL, $month = NULL, $day = NULL)
{
	$output .= _fundcore_currency_summary($year, $month, $day);
	$output .= _fundcore_statistics($year, $month, $day);
	$output .= _fundcore_browse($year, $month, $day);
	
	return $output;	
}

function fundcore_page_main()
{
	$content .= '<p><img src="' . variable_get('fundcore_meter_url', '') . '" alt="..." style="margin-bottom: 2px;" />';
	$content .= '<br /><a href="' . variable_get('fundcore_contribution_url', '') . '"><strong>' . t(variable_get('fundcore_contribution_request', '')) . '</strong></a></p>';

	$content .= variable_get('fundcore_message', '');

	$content .= _fundcore_filter($_GET['edit']);
	$content .= _fundcore_results($_GET['edit']);
	return $content;
}

function fundcore_settings()
{
	$form['fundcore_meter_url'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Meter URL'),
	  '#default_value' => variable_get('fundcore_meter_url', ''),
	  '#description' => t('URL of the image to use as the progress meter (not internationalized).'),
	);
	
	$form['fundcore_contribution_request'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Contribution request text'),
	  '#default_value' => variable_get('fundcore_contribution_request', ''),
	  '#description' => t('Short solicitation linked below meter (internationalized).'),
	);

	$form['fundcore_contribution_url'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Contribution URL'),
	  '#default_value' => variable_get('fundcore_contribution_url', ''),
	  '#description' => t('URL for contribution form (not internationalized).'),
	);

	$form['fundcore_message'] = array(
	  '#type' => 'textarea',
	  '#title' => t('Message'),
	  '#default_value' => variable_get('fundcore_message', ''),
	  '#description' => t('Message displayed to visitors (not internationalized).'),
	);
	
	$form['fundcore_default_minimum'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Default minimum for contribution listing'),
	  '#default_value' => variable_get('fundcore_default_minimum', '0'),
	  '#description' => t('Default minimum for contribution listing in default currency.'),
	);
	
	return $form;	
}