<?
$THESCRIPT = "wiki.phtml" ;
#include ( "./specialPages.php" ) ;
include ( "./databaseFunctions.php" ) ;
include ( "./wikiTitle.php" ) ;
include ( "./wikiPage.php" ) ;
include ( "./wikiUser.php" ) ;

function scanText2 ( $fn ) {
	$ret = "" ;

	#CONSTANTS
	$FS = "³" ;
	$FS1 = $FS."1" ;
	$FS2 = $FS."2" ;
	$FS3 = $FS."3" ;

	#READING FILE
	$t = array () ;
	$fd = fopen ( $fn , "r" ) ;
	while (!feof($fd)) {
		$buffer = fgets($fd, 99999);
		array_push ( $t , $buffer ) ;
		}
	fclose ( $fd ) ;

	array_pop ( $t ) ;
	$t = implode ( "" , $t ) ;

	#SPLIT PAGE
	$sp = explode ( $FS1 , $t ) ;

	$x = array_pop ( $sp ) ;
	$sections = explode ( $FS2 , $x ) ;
	foreach ( $sections as $y ) {
		$text = explode ( $FS3 , $y ) ;
		foreach ( $text as $z ) {
			$ret = $z ;
			}
		}

	return $ret ;
	}



function scantext ( $fn ) {
	$fd = fopen ( $fn , "r" ) ;
	$leadingThree = 0 ;
	$n = 0 ;
	$t = array () ;
	while (!feof($fd)) {
		$buffer = fgets($fd, 4096);
		if ( substr ( $buffer , 0 , 1 ) == "³" ) $leadingThree++ ;
		if ( $leadingThree > 0 ) {
			$t[$n] = $buffer ;
			$n++ ;
			}
		}
	fclose ( $fd ) ;

	$c1 = $t[0] ;
	$t[0] = substr ( $c1 , strrpos ( $c1 , "³" ) + 2 ) ;
	$c1 = substr ( $c1 , 0 , strrpos ( $c1 , "³" ) + 2 ) ;

	$c2 = array_pop ( $t ) ;

	$c1 = explode ( "³" , $c1 ) ;
	$c2 = explode ( "³" , $c2 ) ;

	$ret = "" ;
	for ( $a = 0 ; $a < $n ; $a++ ) $ret .= $t[$a] ;
	return $ret ;
	}

function getFileName ( $an ) {
	global $rootDir ;
	$ret = $rootDir ;
	$sd = ucfirst ( substr ( $an , 0 , 1 ) ) ;
	if ( $sd < "A" or $sd > "Z" ) $sd = "other" ;
	$ret .= "$sd/".ucfirst($an).".db" ;
	return $ret ;
	}

function storeInDB ( $title , $text ) {
	$text = str_replace ( "\\'" , "'" , $text ) ;
	$text = str_replace ( "\\\"" , "\"" , $text ) ;
	$title = str_replace ( "\\'" , "'" , $title ) ;
	$title = str_replace ( "\\\"" , "\"" , $title ) ;
	$npage = new wikiPage ;
	$npage->title = $title ;
	$npage->makeAll () ;
	if ( !$npage->doesTopicExist() ) { $MinorEdit = 2 ; $npage->ensureExistence () ; }
	else $npage->backup() ;
	$npage->setEntry ( $text , "conversion" , 0 , "wikipedia conversion script" , 1 ) ;
	}

function getTopics ( $dir ) {
	$ret = array () ;
	
	$mydir = opendir($dir);
	while ($entry = readdir($mydir)) {
		if ($entry != '.' && $entry != '..') {
			if ( is_dir ( "$dir/$entry" ) ) {
				$a = getTopics ( "$dir/$entry" ) ;
				foreach ( $a as $x ) array_push ( $ret , "$entry/$x" ) ;
			} else {
				$x = substr ( $entry , 0 , strlen ( $entry ) - 3 ) ;
				array_push ( $ret , $x ) ;
				}
			}
	}
	closedir($mydir);

	return $ret ;
	}

function dir2DB ( $letter )  {
	global $rootDir ;
	$a = getTopics ( "$rootDir/$letter" ) ;
	foreach ( $a as $an ) {
		print "<b>$an</b><br>\n" ;
		$fn = getFileName ( $an ) ;
		$t = scantext2 ( $fn ) ;
		storeInDB ( $an , $t ) ;
		}
	}

# MAIN PROGRAM
	global $rootDir ;
	$rootDir = "/home/groups/w/wi/wikipedia/htdocs/fpw/wiki-de/lib-http/db/wiki/page/" ;

	global $l ;
	if ( !isset ( $l ) ) $l = 65 ;
	if ( $l == "other" ) $letter = "other" ;
	else $letter = chr ( $l ) ;
	$nl = $l+1 ;
	if ( $letter == "Z" ) $nl = "other" ;

	print "<html><head></head><body>" ;
	dir2DB ( $letter ) ;
	if ( $l != "other" ) print "<META HTTP-EQUIV=Refresh CONTENT=\"0; URL=scandb.phtml?l=$nl\">" ;
	else print "<h1>FINISHED!</h1>" ;
	print "</body></html>" ;
?>