<?
$THESCRIPT = "wiki.phtml" ;
include ( "./specialPages.php" ) ;
include ( "./databaseFunctions.php" ) ;
include ( "./wikiTitle.php" ) ;
include ( "./wikiPage.php" ) ;
include ( "./wikiUser.php" ) ;

# Main program
	global $action , $title , $pageTitle ;
	global $user , $search , $expiration ;
	global $THESCRIPT ;
	$expiration = time()+315360000 ; # Cookies set will expire in ten years from now
	$pageTitle = "" ;
	$user = new WikiUser ;
	$user->scanCookies () ;
	if ( $action == "" ) $action = "view" ;
	if ( $title == "" ) $title = "HomePage" ;
	
	$theTitle = new wikiTitle ;
	$theTitle->title = urldecode ( $title ) ;
	$theTitle->makeSecureTitle () ;
	$title = $theTitle->secureTitle ;

	$action = strtolower ( trim ( $action ) ) ;
	$title = urldecode ( $title ) ;

	if ( isset ( $search ) ) {
		$out = doSearch () ;
		unset ( $search ) ;
	} else  if ( $action == "watch" ) {
		global $mode ;
		$out = watch ( $title , $mode ) ;
	} else if ( $action == "view" ) $out = view ( $title ) ;
	else if ( $action == "edit" ) $out = doEdit ( $title ) ;
	else if ( $action == "history" ) $out = doHistory ( $title ) ;
	else $out = error ( "No such action \"$action\"" ) ;

	global $bodyOptions , $headerScript ;
	$pageTitle = "Wikipedia : ".str_replace ( "_" , " " , $pageTitle ) ;
	$bodyOptions .= $user->options["background"] ;
	$bodyOptions .= $user->options["text"] ;
	$head = "<HTML><HEAD><TITLE>$pageTitle</TITLE> $headerScript </HEAD><BODY $bodyOptions>\n" ;
	$tail = "</BODY></HTML>" ;

	$linkStyle = "style=\"color:blue\"" ;
	if ( $user->options["underlineLinks"] == "no" ) $linkStyle = "style=\"color:blue;text-decoration:none\"" ;
	if ( $user->options["forceLinks"] != "" ) $linkStyle = $user->options["forceLinks"] ;
	$out = str_replace ( "<a href=" , "<a $linkStyle href=" , $out ) ;
	$out = str_replace ( "&lt;a style=\"color:blue\"" , "&lt;a " , $out ) ; # Correcting weird replacement above

	global $append; # For testing
	print $head.$out.$tail.$append ;
?>