#!/bin/sh
if ! getent passwd gmetric > /dev/null; then
	groupadd gmetric
	useradd -d/ -c'ganglia metric daemon' -ggmetric -s/sbin/nologin gmetric
fi
# Automatically added by dh_installinit
if [ -x "/etc/init.d/gmetricd" ]; then
	update-rc.d gmetricd defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d gmetricd start || exit $?
	else
		/etc/init.d/gmetricd start || exit $?
	fi
fi
# End automatically added section
