#! /bin/ksh

. /lib/svc/share/smf_include.sh

getproparg() {
        val=`svcprop -p $1 $SMF_FMRI`
        [ -n "$val" ] && echo $val
}

config=`getproparg supybot/config-file`

[[ -z "$config" ]] && {
	echo >&2 "supybot/config-file property is not set"
	exit 1
}

case "$1" in
	start)
		/usr/bin/supybot -d $config
		;;
	*)
		echo >&2 "usage: $0 start"
		exit 1
		;;
esac
