.TH PWTOOL 8 "June 13, 2007"
.SH NAME
pwtool \- change shell and gecos information
.SH SYNOPSIS
.B pwtool
[-h] -g \fIgecos\fP] [-s \fIshell\fP]
.SH DESCRIPTION
.B pwtool
allows a user to change his login shell and gecos (real name) information in
\fI/etc/passwd\fP.
.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-g \fIgecos\fP
Change gecos (real name) to \fIgecos\fP.
.TP
.B \-s \fIshell\fP
Change login shell to \fIshell\fP.

.SH AUTHOR
pwtool was written by River Tarnell <river@attenuate.org>.
