#! /bin/sh -e
# $URL: svn+ssh://lmamane@svn.debian.org/svn/pkg-mailman/trunk/debian/postrm $
# $Id: postrm 338 2006-08-22 00:09:13Z thijs $

#DEBHELPER#

if [ "$1" = purge ]; then
  # HACK: At present there is no way to ask ucf for registered files
  #       except for directly querying its database.
  if which ucf >/dev/null; then
    echo -n "Purging files from ucf database " >&2
    for file in $(sed -e '\|^[0-9a-fA-F]\+[[:space:]]\+/etc/mailman/|!d' -e 's|^[0-9a-fA-F]\+[[:space:]]\+||' /var/lib/ucf/hashfile); do
      ucf --purge ${file} 2>/dev/null
      echo -n . >&2
    done
    ucf --purge /etc/cron.d/mailman 2>/dev/null
    echo ". done." >&2
  fi
fi

if [ "$1" = purge ]; then
  rm -f /etc/cron.d/mailman 
  rm -rf /etc/mailman
  rm -rf /var/log/mailman
#  rm -rf /var/lib/mailman
fi
