#!/bin/sh -e
# $URL: svn+ssh://svn.debian.org/svn/pkg-mailman/trunk/debian/preinst $
# $Id: preinst 244 2005-11-26 08:00:04Z lmamane $

. /usr/share/debconf/confmodule

if [ "$1" = "install" ]; then
	if ! id -g list > /dev/null 2>&1 ; then
		addgroup --system list
	fi
	if ! id -u list > /dev/null 2>&1 ; then
		adduser --system --home /var/list --ingroup list list
		chsh -s /bin/sh list
	fi
fi

if [ "$1" = "install" -o "$1" = "upgrade" ]; then
	if [ -d /var/lib/mailman/logs -a ! -L /var/lib/mailman/logs ]; then
		echo "Moving the current logs to /var/lib/mailman/logs.old"
		echo "New logs will be generated in /var/log/mailman"
		mv /var/lib/mailman/logs /var/lib/mailman/logs.old
		mkdir /var/log/mailman && true
		chown root:list /var/log/mailman
		chmod 2775 /var/log/mailman
		ln -s /var/log/mailman /var/lib/mailman/logs
		echo -n "Press RETURN to continue"
		read foo
	fi
fi

#DEBHELPER#

# make sure the qfiles directory is empty.
if [ -d /var/lib/mailman/qfiles ] && \
	[ "$(find /var/lib/mailman/qfiles -type f | wc -l)" -ne 0 ]; then
    # uh-oh.
    db_fset mailman/queue_files_present seen false || true
    db_input critical mailman/queue_files_present || true
    db_go
    exit 1
fi

exit 0
