#!/bin/sh -e
# $URL: svn+ssh://lmamane@svn.debian.org/svn/pkg-mailman/trunk/debian/preinst $
# $Id: preinst 333 2006-08-15 13:48:53Z thijs $

. /usr/share/debconf/confmodule

if [ "$1" = "install" ]; then
	if ! id -g list > /dev/null 2>&1 ; then
		addgroup --system list
	fi
	if ! id -u list > /dev/null 2>&1 ; then
		adduser --system --home /var/list --ingroup list list
		chsh -s /bin/sh list
	fi
fi

#DEBHELPER#

# make sure the qfiles directory is empty.
if [ -d /var/lib/mailman/qfiles ] && \
	[ "$(find /var/lib/mailman/qfiles -type f | wc -l)" -ne 0 ]; then
    # uh-oh.
    db_fset mailman/queue_files_present seen false || true
    db_input critical mailman/queue_files_present || true
    db_go
    exit 1
fi

exit 0
