#! /bin/sh -e
#
# prerm script for Debian python packages.
# Written 1998 by Gregor Hoffleit <flight@debian.org>.
#
# $URL: svn+ssh://svn.debian.org/svn/pkg-mailman/trunk/debian/prerm $
# $Id: prerm 39 2004-03-28 21:11:33Z bsb $

# Hack to allow upgrade from broken 2.1.1 installs where stopping
# mailman will fail.  This hack can be removed after sarge+1 is released.

if [ "$1" = "failed-upgrade" -a \( "$2" = "2.1.1-1" -o \
     "$2" = "2.1.1-2" -o "$2" = "2.1.1-3" \) ]; then
  if [ -x "/etc/init.d/mailman" ]; then
    if [ -x /usr/sbin/invoke-rc.d ] ; then
   	  invoke-rc.d mailman stop || true
    else
      /etc/init.d/mailman stop || true
    fi
  fi
  chmod -x /usr/lib/mailman/bin/mailmanctl
fi

if [ "$1" = "failed-upgrade" ] && dpkg --compare-versions "$2" gt "2.1.4-2" ; then
  if [ -x "/etc/init.d/mailman" ]; then
    if [ -x /usr/sbin/invoke-rc.d ] ; then
      invoke-rc.d mailman stop || true
    else
      /etc/init.d/mailman stop || true
    fi
  fi
  chmod -x /usr/lib/mailman/bin/mailmanctl
fi

#DEBHELPER#

PACKAGE=mailman

dpkg --listfiles $PACKAGE |
	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
	xargs rm -f >&2
