# Six degrees of Wikipedia: Makefile
# This source code is released into the public domain.
#
# $Id$

include ../rules.mk

LIBRARY	= libsdstore.a
SRCS	= bdb_adjacency_store.cc
OBJS	= $(SRCS:.cc=.o)

include ../frag/cxxlib.mk
