#!/bin/sh
#

if [[ "$1" == "" ]]; then CLASS=WikiSuite; else CLASS=$1; fi
echo Running $CLASS

java -classpath ./build:jars/httpunit.jar:jars/nekohtml.jar:jars/xercesImpl.jar:jars/xml-apis.jar com.piclab.wikitest.$CLASS

