<?php
#Internationalisation message file of Record Admin extension

$messages=array();

$messages['en'] = array (
	'recordadmin' => 'Record Administration',
	'recordadmin-desc' => 'A special page for finding and editing record articles using a form',
	'recordadmin-select' => 'Select the type of record to search for ',
	'recordadmin-newsearch' => 'New $1 search',
	'recordadmin-newrecord' => 'Select another record type',
	'recordadmin-submit' => 'Submit',
	'recordadmin-create' => 'Find or Create a "$1" record',
	'recordadmin-alreadyexist' => 'Sorry, "$1" already exists!',
	'recordadmin-createsuccess' => '$1 created successfully',
	'recordadmin-createerror' => 'An error occurred while attempting to create the $1!',
	'recordadmin-badtitle' => 'Bad title!',
	'recordadmin-recordid' => 'Record ID:',
	'recordadmin-invert' => 'Invert selection',
	'recordadmin-buttonsearch' => 'Search',
	'recordadmin-buttoncreate' => 'Create',
	'recordadmin-buttonreset' => 'Reset',
	'recordadmin-searchresult' => 'Search results',
	'recordadmin-nomatch' => 'No matching records found!',
	'recordadmin-edit' => 'Editing $1',
	'recordadmin-typeupdated' => '$1 properties updated',
	'recordadmin-updatesuccess' => '$1 updated successfully',
	'recordadmin-updateerror' => 'An error occurred during update',
	'recordadmin-buttonsave' => 'Save',
	'recordadmin-noform' => 'There is no form associated with "$1" records!',
	'recordadmin-createlink' => 'click <a href=$1>here</a> to create one',
	'recordadmin-newcreated' => 'New $type created from public form',
);

$messages['fr'] = array (
	'recordadmin' => 'Gestion des enregistrements',
	'recordadmin-desc' => 'Une page spéciale pour trouver et modifier l’enregistrement des articles par l’utilisation d’un formulaire',
	'recordadmin-select' => 'Sélectionner le type d’enregistrement à rechercher pour',
	'recordadmin-newsearch' => 'Nouvelle recherche $1',
	'recordadmin-newrecord' => 'Sélectionner un autre type d’enregistrement',
	'recordadmin-submit' => 'Soumettre',
	'recordadmin-create' => 'Chercher ou créer un enregistrement « $1 »',
	'recordadmin-alreadyexist' => 'Désolé, « $1 » existe déjà !',
	'recordadmin-createsuccess' => '$1 creé avec succès',
	'recordadmin-createerror' => 'Une erreur est intervenue lors de la tentative de création de $1 !',
	'recordadmin-badtitle' => 'Mauvais titre!',
	'recordadmin-recordid' => 'Enregistrement ID :',
	'recordadmin-invert' => 'Inverser la sélection',
	'recordadmin-buttonsearch' => 'Rechercher',
	'recordadmin-buttoncreate' => 'Créer',
	'recordadmin-buttonreset' => 'Réinitialiser',
	'recordadmin-nomatch' => 'Aucun enregistrement correspondant de trouvé !',
	'recordadmin-edit' => 'Modifier $1',
	'recordadmin-typeupdated' => 'propriété de $1 mises à jour',
	'recordadmin-updatesuccess' => '$1 mis à jour avec succès',
	'recordadmin-updateerror' => 'Une erreur a été rencontrée lors de la mise à jour',
	'recordadmin-buttonsave' => 'Sauvegarder',
	'recordadmin-noform' => 'Il n’y a aucun formulaire avec l’enregistrement « $1 » !',
	'recordadmin-createlink' => 'cliquez <a href=$1>ici</a> pour en créer un',
);
