<!-- ++++++++++ DONATEBOX begin ++++++++++ -->
<!-- ADJUST LINK to donate page here -->
<form action="...">
  <table border="0" cellspacing="0" cellpadding="0" width="321">

    <!-- First line -->
    <tr>
      <td valign="top" colspan="4">
        <img src="/sites/all/modules/fundcore_frontpage/images/donatebox-top.jpg" width="321" height="63" alt="donatebox-top">
      </td>
    </tr>

    <!-- Second line -->
    <tr>
      <td width="21" height="33" valign="top" style="border-top-width:0px; border-bottom-width:0px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
      <td valign="top" width="105" style="background-color:#f8e5bb">
        <img src="/sites/all/modules/fundcore_frontpage/images/payment-first-line.gif" alt="Payment methods">
      </td>
      <td valign="top" align="left" style="background-color:#f8e5bb">
        <!-- ADJUST end -->
        <input name="amount" type="text" size="8">&nbsp;&nbsp;
        <select name="currency" size="1">
          <option selected="selected">USD</option>
          <option>EUR</option>
          <option>ZAR</option>
        </select>
      </td>
      <td width="21" valign="top" style="border-top-width:0px; border-bottom-width:0px; border-left-width:0px; border-right-width:1px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
    </tr>

    <!-- Third line -->
    <tr>
      <td width="21" height="33" valign="top" style="border-top-width:0px; border-bottom-width:0px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
      <td colspan="2" valign="top" align="left" height="27" style="background-color:#f8e5bb">
        <img src="/sites/all/modules/fundcore_frontpage/images/payment-second-line.gif" alt="Payment methods"></td>
      <td width="21" valign="top" style="border-top-width:0px; border-bottom-width:0px; border-left-width:0px; border-right-width:1px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
    </tr>

    <!-- Fourth line -->
    <tr>
      <td width="21" valign="top" style="border-top-width:0px; border-bottom-width:0px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
      <td colspan="2" valign="top" align="left" style="background-color:#f8e5bb">
        <div class="tax-exemption">
          <br>
          <!-- INSERT TEXT -->
          The Wikimedia Foundation is a <b>501(c)(3) tax exempt charitable corporation</b>. You may deduct donations from your federally-taxable income.
          <!-- END INSERT -->
        </div>
      </td>
      <td width="21"  valign="top" style="border-top-width:0px; border-bottom-width:0px; border-left-width:0px; border-right-width:1px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
    </tr>

    <!-- Fifth line -->
    <tr>
      <td width="21" height="64" valign="top" style="border-top-width:0px; border-bottom-width:1px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
      </td>
      <td colspan="2" valign="top" align="right" style="border-top-width:0px; border-bottom-width:1px; border-left-width:0px; border-right-width:0px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        <br>
        <input type="image" src="/sites/all/modules/fundcore_frontpage/images/button-donate-now.gif" alt="Donate now">
      </td>
      <td width="21"  valign="top" style="border-top-width:0px; border-bottom-width:1px; border-left-width:0px; border-right-width:1px; border-style:solid; border-color:#e9a95e; background-color:#f8e5bb">
        &nbsp;
    </td></tr>

  </table>
</form>
<!-- ++++++++++ DONATEBOX end ++++++++++ -->
