<!-- ++++++++++ OTHERBOX begin ++++++++++ -->
<table border="0" cellspacing="0" cellpadding="0" width="321">

  <tr>
    <td style="background-color:#ececec;">
      <ul class="tabmenu" style="display: none" id="deposit">
        <li><a id="deposit-a-0" class="active">Bank transfer</a></li>
        <li><a id="deposit-a-1" href="javascript:tab('deposit',1)">Send a cheque</a></li>
      </ul>
      <div class="tabmenu-pane" id="deposit-pane-0">
        <p><b>Deposit money into our bank account:</b></p>
        <p>Account holder: Wikimedia Foundation<br>
        Account: 068-9999995-01</p>
        <p>Bank: Dexia bank/Banque Dexia<br>
        IBAN: BE43 0689 9999 9501<br>
        BIC: GKCCBEBB</p>
      </div>
      <div class="tabmenu-pane" id="deposit-pane-1">
        TODO Cheque
      </div>
      <!-- Hide the second pane (semi-compatible with non-JS browsers -->
      <script type="text/javascript">tab('deposit', 0);</script>
    </td>
  </tr>

</table>

<!-- ++++++++++ OTHERBOX end ++++++++++ -->