<!-- ++++++++++ VIDEOBOX begin ++++++++++ -->
<table border="0" cellspacing="0" cellpadding="0" width="463">
  <!-- First line -->
  <tr>
    <td colspan="4"><img src="/sites/all/modules/fundcore_frontpage/images/videobox-top.jpg" width="463" height="17" alt="border-top"></td>
  </tr>
  <!-- Second line -->
  <tr>
    <td colspan="4"><img src="/sites/all/modules/fundcore_frontpage/images/imagine-a-world.gif" width="463" height="75" alt="Imagine a world..."></td>
  </tr>
  <!-- Third line -->
  <tr>
    <td colspan="4" height="18" style="border-top-width:0px; border-bottom-width:0px; border-left-width:1px; border-right-width:1px; border-style:solid; border-color:#c2c2c2; background-color:#ffffff">
      &nbsp;
    </td>
  </tr>
  <!-- Fourth line -->
  <tr>
    <td width="61" style="border-top-width:0px; border-bottom-width:0px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#c2c2c2; background-color:#ffffff">
      &nbsp;
    </td>

    <td valign="top" style="background-color:#ffffff;">
      <!-- INSERT YOUTUBE VIDEO (Take care to adjust height to 217px and width to 263px) -->
      <object width="263" height="217">
        <param name="movie" value="http://www.youtube.com/v/y6mCO5lXsSU&rel=1"></param>
        <param name="wmode" value="transparent"></param>
        <embed src="http://www.youtube.com/v/y6mCO5lXsSU&rel=1" type="application/x-shockwave-flash" wmode="transparent" width="263" height="217"></embed>
      </object>
      <!-- END INSERT -->
    </td>

    <td width="32" style="background-color:#ffffff"></td><td width="107" valign="bottom" align="right" style="border-top-width:0px; border-bottom-width:0px; border-left-width:0px; border-right-width:1px; border-style:solid; border-color:#c2c2c2; background-color:#ffffff"><img src="/sites/all/modules/fundcore_frontpage/images/jimbo-top.jpg" width="106" height="94" alt="Jimbo portrait top"></td></tr>
  <!-- Fifth line -->
  <tr>
    <td style="border-top-width:0px; border-bottom-width:0px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#c2c2c2; background-color:#ffffff;">
      &nbsp;
    </td>
    <td align="right" style="background-color:#ffffff;">
      <div id="videooptions">
        <!-- INSERT REFERENCE to video options -->
        <a href="http://wikimediafoundation.org/donate/2007/psa/" target="_blank">Click here</a> for video playback options.
        <!-- END INSERT -->
      </div>
    </td>
    <td align="right" colspan="2" height="29" style="border-top-width:0px; border-bottom-width:0px; border-left-width:0px; border-right-width:0px; border-style:solid; border-color:#c2c2c2; background-color:#ffffff">
      <img src="/sites/all/modules/fundcore_frontpage/images/jimbo-middle.jpg" width="107" height="29" alt="Jimbo portrait middle">
    </td>
  </tr>
  <!-- Sixth line -->
  <tr>
    <td colspan="4">
      <img src="/sites/all/modules/fundcore_frontpage/images/videobox-bottom.jpg" width="463" height="14" alt="border-bottom">
    </td>
  </tr>
</table>
<!-- ++++++++++ VIDEOBOX end ++++++++++++ -->