<!-- ++++++++++ WHATWENEEDBOX begin ++++++++++ -->
<table border="0" cellspacing="0" cellpadding="0" width="321">

  <!-- Box header -->
  <tr>
    <td>
      <img src="/sites/all/modules/fundcore_frontpage/images/box-header-left.jpg" width="17" height="30">
    </td>
    <td align="left" width="287" style="background-image:url(/sites/all/modules/fundcore_frontpage/images/box-header-background.gif); background-repeat:repeat-x;">
      <!-- INSERT BOX TITLE -->What we need the money for<!-- END INSERT -->
    </td>
    <td>
      <img src="/sites/all/modules/fundcore_frontpage/images/box-header-right.jpg" width="17" height="30">
    </td>
  </tr>
  <!-- Box content -->
  <tr>
    <td height="200" style="border-top-width:0px; border-bottom-width:1px; border-left-width:1px; border-right-width:0px; border-style:solid; border-color:#d0d0d0; background-color:#ffffff">
      &nbsp;
    </td>
    <td valign="top" style="border-top-width:0px; border-bottom-width:1px; border-left-width:0px; border-right-width:0px; border-style:solid; border-bottom-color:#d0d0d0; background-color:#ffffff">
      <br>
      <img src="/sites/all/modules/fundcore_frontpage/images/planned-spending-distribution.jpg" height="157" width="287" alt="Planned spendign distribution">
      <br>
      <br>
      <div class="whatweneed">
        <!-- INSERT TEXT -->
        <p>Please read our latest <a href="http://upload.wikimedia.org/wikipedia/foundation/2/28/Wikimedia_2006_fs.pdf">financial report</a> (PDF) and have a look at our <a href="http://meta.wikimedia.org/wiki/Wikimedia_servers/hardware_orders">list of the hardware we ordered</a> after our last fundraising drive.</p>
        <p>Do you have more questions about our current fundraising drive? Please read our <a href="http://wikimediafoundation.org/wiki/Fundraising_FAQ">Fundraising FAQ</a>.
        </p>
        <!-- END INSERT -->
        <br>
      </div>
    </td>
    <td style="border-top-width:0px; border-bottom-width:1px; border-left-width:0px; border-right-width:1px; border-style:solid; border-color:#d0d0d0; background-color:#ffffff">
      &nbsp;
    </td>
  </tr>
</table>
<!-- ++++++++++ WHATWENEEDBOX end ++++++++++++ -->