#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
Copyright (C) 2010 by Diederik van Liere (dvanliere@gmail.com)
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 2
as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details, at
http://www.fsf.org/licenses/gpl.html
'''

__author__ = '''\n'''.join(['Diederik van Liere (dvanliere@gmail.com)', ])
__author__email = 'dvanliere at gmail dot com'
__date__ = '2010-10-21'
__version__ = '0.1'

'''
This file provides mapper between language name and locale language name and 
Wikipedia acronym. 
Gothic and Birmese are not yet supported, see rows 450 and 554. 
'''

LANGUAGES = {
'English':'en',
'German':'de',
'French':'fr',
'Italian':'it',
'Polish':'pl',
'Japanese':'ja',
'Spanish':'es',
'Dutch':'nl',
'Portuguese':'pt',
'Russian':'ru',
'Swedish':'sv',
'Chinese':'zh',
'Catalan':'ca',
'Norwegian':'no',
'Bokmål':'no',
'Finnish':'fi',
'Ukrainian':'uk',
'Hungarian':'hu',
'Czech':'cs',
'Romanian':'ro',
'Turkish':'tr',
'Korean':'ko',
'Vietnamese':'vi',
'Danish':'da',
'Arabic':'ar',
'Esperanto':'eo',
'Serbian':'sr',
'Indonesian':'id',
'Lithuanian':'lt',
'Volapük':'vo',
'Slovak':'sk',
'Hebrew':'he',
'Bulgarian':'bg',
'Persian':'fa',
'Slovenian':'sl',
'Waray-Waray':'war',
'Croatian':'hr',
'Estonian':'et',
'Malay':'ms',
'Newar':'new',
'Nepal Bhasa':'new',
'Simple English':'simple',
'Galician':'gl',
'Thai':'th',
'Aromanian':'roa-rup',
'Nynorsk':'nn',
'Basque':'eu',
'Hindi':'hi',
'Greek':'el',
'Haitian':'ht',
'Latin':'la',
'Telugu':'te',
'Georgian':'ka',
'Cebuano':'ceb',
'Macedonian':'mk',
'Azeri':'az',
'Tagalog':'tl',
'Breton':'br',
'Serbo-Croatian':'sh',
'Marathi':'mr',
'Luxembourgish':'lb',
'Javanese':'jv',
'Latvian':'lv',
'Bosnian':'bs',
'Icelandic':'is',
'Welsh':'cy',
'Belarusian':'be-x-old',
'Taraškievica':'be-x-old',
'Piedmontese':'pms',
'Albanian':'sq',
'Tamil':'ta',
'Bishnupriya Manipuri':'bpy',
'Belarusian':'be',
'Aragonese':'an',
'Occitan':'oc',
'Bengali':'bn',
'Swahili':'sw',
'Ido':'io',
'Ripuarian':'ksh',
'Lombard':'lmo',
'West Frisian':'fy',
'Gujarati':'gu',
'Low Saxon':'nds',
'Afrikaans':'af',
'Sicilian':'scn',
'Quechua':'qu',
'Kurdish':'ku',
'Urdu':'ur',
'Sundanese':'su',
'Malayalam':'ml',
'Cantonese':'zh-yue',
'Asturian':'ast',
'Neapolitan':'nap',
'Samogitian':'bat-smg',
'Walloon':'wa',
'Chuvash':'cv',
'Irish':'ga',
'Armenian':'hy',
'Yoruba':'yo',
'Kannada':'kn',
'Tajik':'tg',
'Tarantino':'roa-tara',
'Venetian':'vec',
'Western Panjabi':'pnb',
'Nepali':'ne',
'Scottish Gaelic':'gd',
'Yiddish':'yi',
'Min Nan':'zh-min-nan',
'Uzbek':'uz',
'Tatar':'tt',
'Kapampangan':'pam',
'Ossetian':'os',
'Sakha':'sah',
'Alemannic':'als',
'Maori':'mi',
'Egyptian Arabic':'arz',
'Kazakh':'kk',
'Nahuatl':'nah',
'Limburgian':'li',
'Upper Sorbian':'hsb',
'Gilaki':'glk',
'Corsican':'co',
'Gan':'gan',
'Amharic':'am',
'Mongolian':'mn',
'Interlingua':'ia',
'Central Bicolano':'bcl',
'Võro':'fiu-vro',
'Dutch Low Saxon':'nds-nl',
'Faroese':'fo',
'Turkmen':'tk',
'Scots':'sco',
'West Flemish':'vls',
'Sinhalese':'si',
'Sanskrit':'sa',
'Bavarian':'bar',
'Burmese':'my',
'Manx':'gv',
'Divehi':'dv',
'Norman':'nrm',
'Pangasinan':'pag',
'Romansh':'rm',
'Banyumasan':'map-bms',
'Zazaki':'diq',
'Sorani':'ckb',
'Northern Sami':'se',
'Mazandarani':'mzn',
'Wu':'wuu',
'Uyghur':'ug',
'Friulian':'fur',
'Ligurian':'lij',
'Maltese':'mt',
'Bihari':'bh',
'Novial':'nov',
'Malagasy':'mg',
'Kashubian':'csb',
'Ilokano':'ilo',
'Sardinian':'sc',
'Classical Chinese':'zh-classical',
'Khmer':'km',
'Ladino':'lad',
'Pali':'pi',
'Anglo-Saxon':'ang',
'Zamboanga Chavacano':'cbk-zam',
'Tibetan':'bo',
'Fiji Hindi':'hif',
'Franco-Provençal':'frp',
'Arpitan':'frp',
'Hakka':'hak',
'Cornish':'kw',
'Punjabi':'pa',
'Pashto':'ps',
'Kalmyk':'xal',
'Silesian':'szl',
'Pennsylvania German':'pdc',
'Hawaiian':'haw',
'Saterland Frisian':'stq',
'Interlingue':'ie',
'Navajo':'nv',
'Fijian':'fj',
'Crimean Tatar':'crh',
'Komi':'kv',
'Tongan':'to',
'Acehnese':'ace',
'Somali':'so',
'Erzya':'myv',
'Guarani':'gn',
'Karachay-Balkar':'krc',
'Extremaduran':'ext',
'Lingala':'ln',
'Kirghiz':'ky',
'Meadow Mari':'mhr',
'Assyrian Neo-Aramaic':'arc',
'Emilian-Romagnol':'eml',
'Lojban':'jbo',
'Picard':'pcd',
'Aymara':'ay',
'Wolof':'wo',
'Tumbuka':'tum',
'Kabyle':'kab',
'Bashkir':'ba',
'North Frisian':'frr',
'Tahitian':'ty',
'Tok Pisin':'tpi',
'Papiamentu':'pap',
'Zealandic':'zea',
'Sranan':'srn',
'Greenlandic':'kl',
'Udmurt':'udm',
'Chechen':'ce',
'Igbo':'ig',
'Komi-Permyak':'koi',
'Oriya':'or',
'Lower Sorbian':'dsb',
'Kongo':'kg',
'Lao':'lo',
'Abkhazian':'ab',
'Moksha':'mdf',
'Romani':'rmy',
'Hill Mari':'mrj',
'Banjar':'bjn',
'Old Church Slavonic':'cu',
'Mirandese':'mwl',
'Karakalpak':'kaa',
'Samoan':'sm',
'Moldovan':'mo',
'Tetum':'tet',
'Avar':'av',
'Kashmiri':'ks',
'Gothic':'got',
'Sindhi':'sd',
'Bambara':'bm',
'Nauruan':'na',
'Norfolk':'pih',
'Pontic':'pnt',
'Inuktitut':'iu',
'Inupiak':'ik',
'Bislama':'bi',
'Cherokee':'chr',
'Assamese':'as',
'Min Dong':'cdo',
'Ewe':'ee',
'Swati':'ss',
'Oromo':'om',
'Zhuang':'za',
'Zulu':'zu',
'Tigrinya':'ti',
'Venda':'ve',
'Tsonga':'ts',
'Hausa':'ha',
'Dzongkha':'dz',
'Sango':'sg',
'Chamorro':'ch',
'Cree':'cr',
'Xhosa':'xh',
'Akan':'ak',
'Sesotho':'st',
'Kinyarwanda':'rw',
'Tswana':'tn',
'Kikuyu':'ki',
'Buryat':'bxr',
'Buginese':'bug',
'Chichewa':'ny',
'Lak':'lbe',
'Twi':'tw',
'Shona':'sn',
'Kirundi':'rn',
'Fula':'ff',
'Cheyenne':'chy',
'Luganda':'lg',
'Ndonga':'ng',
'Sichuan Yi':'ii',
'Choctaw':'cho',
'Marshallese':'mh',
'Afar':'aa',
'Kuanyama':'kj',
'Hiri Motu':'ho',
'Muscogee':'mus',
'Kanuri':'kr',
'Herero':'hz',
'English':'en',
'Deutsch':'de',
'Français':'fr',
'Italiano':'it',
'Polski':'pl',
'日本語':'ja',
'Español':'es',
'Nederlands':'nl',
'Português':'pt',
'Русский':'ru',
'Svenska':'sv',
'中文':'zh',
'Català':'ca',
'Norsk':'no',
'Bokmål':'no',
'Suomi':'fi',
'Українська':'uk',
'Magyar':'hu',
'Čeština':'cs',
'Română':'ro',
'Türkçe':'tr',
'한국어':'ko',
'Tiếng Việt':'vi',
'Dansk':'da',
'العربية':'ar',
'Esperanto':'eo',
'Српски':'sr',
'Srpski':'sr',
'Bahasa Indonesia':'id',
'Lietuvių':'lt',
'Volapük':'vo',
'Slovenčina':'sk',
'עברית':'he',
'Български':'bg',
'فارسی':'fa',
'Slovenščina':'sl',
'Winaray':'war',
'Hrvatski':'hr',
'Eesti':'et',
'Bahasa Melayu':'ms',
'नेपाल भाषा':'new',
'Simple English':'simple',
'Galego':'gl',
'ไทย':'th',
'Armãneashce':'roa-rup',
'Nynorsk':'nn',
'Euskara':'eu',
'हिन्दी':'hi',
'Ελληνικά':'el',
'Krèyol ayisyen':'ht',
'Latina':'la',
'తెలుగు':'te',
'ქართული':'ka',
'Sinugboanong Binisaya':'ceb',
'Македонски':'mk',
'Azərbaycan':'az',
'Tagalog':'tl',
'Brezhoneg':'br',
'Srpskohrvatski':'sh',
'Српскохрватски':'sh',
'मराठी':'mr',
'Lëtzebuergesch':'lb',
'Basa Jawa':'jv',
'Latviešu':'lv',
'Bosanski':'bs',
'Íslenska':'is',
'Cymraeg':'cy',
'Беларуская':'be-x-old',
'тарашкевіца':'be-x-old',
'Piemontèis':'pms',
'Shqip':'sq',
'தமிழ்':'ta',
'ইমার ঠার':'bpy',
'বিষ্ণুপ্রিয়া মণিপুরী':'bpy',
'Беларуская':'be',
'Aragonés':'an',
'Occitan':'oc',
'বাংলা':'bn',
'Kiswahili':'sw',
'Ido':'io',
'Ripoarisch':'ksh',
'Lumbaart':'lmo',
'Frysk':'fy',
'ગુજરાતી':'gu',
'Plattdüütsch':'nds',
'Afrikaans':'af',
'Sicilianu':'scn',
'Runa Simi':'qu',
'Kurdî':'ku',
'كوردی':'ku',
'اردو':'ur',
'Basa Sunda':'su',
'മലയാളം':'ml',
'粵語':'zh-yue',
'Asturianu':'ast',
'Nnapulitano':'nap',
'Žemaitėška':'bat-smg',
'Walon':'wa',
'Чăваш':'cv',
'Gaeilge':'ga',
'Հայերեն':'hy',
'Yorùbá':'yo',
'ಕನ್ನಡ':'kn',
'Тоҷикӣ':'tg',
'Tarandíne':'roa-tara',
'Vèneto':'vec',
'شاہ مکھی پنجابی':'pnb',
'Shāhmukhī Pañjābī':'pnb',
'नेपाली':'ne',
'Gàidhlig':'gd',
'ייִדיש':'yi',
'Bân-lâm-gú':'zh-min-nan',
'O‘zbek':'uz',
'Tatarça':'tt',
'Татарча':'tt',
'Kapampangan':'pam',
'Иронау':'os',
'Саха тыла':'sah',
'Saxa Tyla':'sah',
'Alemannisch':'als',
'Māori':'mi',
'مصرى':'arz',
'Maṣrī':'arz',
'Қазақша':'kk',
'Nāhuatl':'nah',
'Limburgs':'li',
'Hornjoserbsce':'hsb',
'گیلکی':'glk',
'Corsu':'co',
'贛語':'gan',
'አማርኛ':'am',
'Монгол':'mn',
'Interlingua':'ia',
'Bikol':'bcl',
'Võro':'fiu-vro',
'Nedersaksisch':'nds-nl',
'Føroyskt':'fo',
'تركمن ':'tk',
'Туркмен':'tk',
'Scots':'sco',
'West-Vlams':'vls',
'සිංහල':'si',
'संस्कृतम्':'sa',
'Boarisch':'bar',
'မ္ရန္‌မာစာ':'my', #Needs fix
'Gaelg':'gv',
'ދިވެހިބަސް':'dv',
'Nouormand':'nrm',
'Normaund':'nrm',
'Pangasinan':'pag',
'Rumantsch':'rm',
'Basa Banyumasan':'map-bms',
'Zazaki':'diq',
'Soranî':'ckb',
'کوردی':'ckb',
'Sámegiella':'se',
'مَزِروني':'mzn',
'吴语':'wuu',
'Oyghurque':'ug',
'Furlan':'fur',
'Líguru':'lij',
'Malti':'mt',
'भोजपुरी':'bh',
'Novial':'nov',
'Malagasy':'mg',
'Kaszëbsczi':'csb',
'Ilokano':'ilo',
'Sardu':'sc',
'古文':'zh-classical',
'文言文':'zh-classical',
'ភាសាខ្មែរ':'km',
'Dzhudezmo':'lad',
'पाऴि':'pi',
'Englisc':'ang',
'Chavacano de Zamboanga':'cbk-zam',
'བོད་སྐད':'bo',
'Fiji Hindi':'hif',
'Arpitan':'frp',
'Hak-kâ-fa':'hak',
'客家話':'hak',
'Kernewek':'kw',
'Karnuack':'kw',
'ਪੰਜਾਬੀ':'pa',
'پښتو':'ps',
'Хальмг':'xal',
'Ślůnski':'szl',
'Deitsch':'pdc',
'Hawai`i':'haw',
'Seeltersk':'stq',
'Interlingue':'ie',
'Diné bizaad':'nv',
'Na Vosa Vakaviti':'fj',
'Qırımtatarca':'crh',
'Коми':'kv',
'faka Tonga':'to',
'Bahsa Acèh':'ace',
'Soomaaliga':'so',
'Эрзянь':'myv',
'Erzjanj Kelj':'myv',
"Avañe'ẽ":'gn',
'Къарачай-Малкъар':'krc',
'Qarachay-Malqar':'krc',
'Estremeñu':'ext',
'Lingala':'ln',
'Кыргызча':'ky',
'Олык Марий':'mhr',
'Olyk Marij':'mhr',
'ܐܪܡܝܐ':'arc',
'Emiliàn e rumagnòl':'eml',
'Lojban':'jbo',
'Picard':'pcd',
'Aymar':'ay',
'Wolof':'wo',
'chiTumbuka':'tum',
'Taqbaylit':'kab',
'Башҡорт':'ba',
'Frasch':'frr',
'Reo Mā`ohi':'ty',
'Tok Pisin':'tpi',
'Papiamentu':'pap',
'Zeêuws':'zea',
'Sranantongo':'srn',
'Kalaallisut':'kl',
'Удмурт кыл':'udm',
'Нохчийн':'ce',
'Igbo':'ig',
'Перем Коми':'koi',
'Perem Komi':'koi',
'ଓଡ଼ିଆ':'or',
'Dolnoserbski':'dsb',
'KiKongo':'kg',
'ລາວ':'lo',
'Аҧсуа':'ab',
'Мокшень':'mdf',
'Mokshanj Kälj':'mdf',
'romani - रोमानी':'rmy',
'Кырык Мары':'mrj',
'Kyryk Mary':'mrj',
'Bahasa Banjar':'bjn',
'Словѣньскъ':'cu',
'Páigina Percipal':'mwl',
'Qaraqalpaqsha':'kaa',
'Gagana Samoa':'sm',
'Молдовеняскэ':'mo',
'Tetun':'tet',
'Авар':'av',
'कश्मीरी':'ks',
'كشميري':'ks',
'𐌲𐌿𐍄𐌹𐍃𐌺':'got',   #Needs fix
'سنڌي، سندھی ، सिन्ध':'sd',
'Bamanankan':'bm',
'dorerin Naoero':'na',
'Norfuk':'pih',
'Ποντιακά':'pnt',
'ᐃᓄᒃᑎᑐᑦ':'iu',
'Iñupiak':'ik',
'Bislama':'bi',
'ᏣᎳᎩ':'chr',
'অসমীয়া':'as',
'Mìng-dĕ̤ng-ngṳ̄':'cdo',
'Eʋegbe':'ee',
'SiSwati':'ss',
'Oromoo':'om',
'Cuengh':'za',
'isiZulu':'zu',
'ትግርኛ':'ti',
'Tshivenda':'ve',
'Xitsonga':'ts',
'هَوُسَ':'ha',
'ཇོང་ཁ':'dz',
'Sängö':'sg',
'Chamoru':'ch',
'Nehiyaw':'cr',
'isiXhosa':'xh',
'Akana':'ak',
'Sesotho':'st',
'Ikinyarwanda':'rw',
'Setswana':'tn',
'Gĩkũyũ':'ki',
'Буряад':'bxr',
'Basa Ugi':'bug',
'Chi-Chewa':'ny',
'Лакку':'lbe',
'Twi':'tw',
'chiShona':'sn',
'Kirundi':'rn',
'Fulfulde':'ff',
'Tsetsêhestâhese':'chy',
'Luganda':'lg',
'Oshiwambo':'ng',
'ꆇꉙ':'ii',
'Choctaw':'cho',
'Ebon':'mh',
'Afar':'aa',
'Kuanyama':'kj',
'Hiri Motu':'ho',
'Muskogee':'mus',
'Kanuri':'kr',
'Otsiherero':'hz',
}