#!/bin/sh

set -e
set -x

# Redo network configuration statically
echo d-i netcfg/get_ipaddress string $(ifconfig | grep "inet addr" | cut -d ' ' -f 12 | sed 's/addr://' | grep -v 127\.0\.0\.1) > /tmp/static_net.cfg
debconf-set-selections /tmp/static_net.cfg
killall.sh; netcfg; true

# Preseed the correct wikimedia repository location
SUITE=$(debconf-get mirror/suite)
echo d-i apt-setup/local0/repository string  http://apt.wikimedia.org/wikimedia $SUITE-wikimedia main restricted universe multiverse > /tmp/apt_repository.cfg
debconf-set-selections /tmp/apt_repository.cfg
