#!/bin/sh

set -e
set -x

# Redo network configuration statically
echo d-i netcfg/get_ipaddress string $(ifconfig | grep "inet addr" | cut -d ' ' -f 12 | sed 's/addr://' | grep -v 127\.0\.0\.1) > /tmp/static_net.cfg
debconf-set-selections /tmp/static_net.cfg
killall.sh; netcfg; true

# Preseed the correct wikimedia repository location
SUITE=$(debconf-get mirror/suite)
echo d-i apt-setup/local0/repository string  http://apt.wikimedia.org/wikimedia $SUITE-wikimedia main restricted universe multiverse > /tmp/apt_repository.cfg
debconf-set-selections /tmp/apt_repository.cfg

# Start httpd server for debug logs over the network
# The httpd serves files from /var/log, where almost
# everything of interest is. Link a few other useful files to
# there.
ln -sf /etc/lsb-release /var/log
ln -sf /var/lib/dpkg/status /var/log
ln -sf /usr/share/save-logs/install-report.template /var/log

# Kill existing server if one is already running
: >/var/lib/httpd_stop # Blocks new listener processes from starting
sleep 1
for PID in $(pidof nc); do
	if grep -q "httpd" /proc/$PID/cmdline ; then
		# The server may already have gone if hit
		kill $PID 2>/dev/null || true
	fi
done
rm /var/lib/httpd_stop
#httpd
