#!/bin/sh

set -e

# Install wikimedia-base which pulls in a lot of other stuff, and
# openssh-server just to be sure
apt-install wikimedia-base openssh-server

# Install the public root ssh key
mkdir /target/root/.ssh
wget -O /target/root/.ssh/authorized_keys http://apt.wikimedia.org/autoinstall/ssh/authorized_keys
chmod go-rwx /target/root/.ssh/authorized_keys

# Do not let Ubuntu installer disable the console
[ -f /usr/lib/prebaseconfig.d/90console ] && rm -f /usr/lib/prebaseconfig.d/90console
[ -f /usr/lib/finish-install.d/90console ] && rm -f /usr/lib/finish-install.d/90console

# Enable serial console
if [ -f /target/etc/inittab ]
then
	sed -i -e "s/^#T0:/T0:/" /target/etc/inittab
fi

# Change /etc/motd to read the auto-install date
if [ -f /etc/motd.tail ]
then
	# Edgy
	in-target 'echo -e $(cat /etc/issue.net) auto-installed on $(date). > /etc/motd.tail'
else
	# Dapper
	chroot /target /bin/sh -c 'echo -e \\n$(cat /etc/issue.net) auto-installed on $(date). > /etc/motd'
fi
