<?
/* yearbook.phtml - Wikipedia Yearbook main program
 * Copyright (C) 2001  Simon James Kissane
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/* controls page appearance */
$bodyattrs = "bgcolor=\"#fffff0\"";

/* load modules */
require ("./yearbook-cal.php"); /* calendar-related utilities */
require ("./yearbook-display.php"); /* display-related utilities */
require ("./yearbook-wiki.php"); /* wiki formatting functions */
require ("./yearbook-db.php"); /* database functions */
require ("./yearbook-pages.php"); /* code to display yearbook pages */
require ("./yearbook-edit.php"); /* code to edit yearbook entries */

/* initialize database */
init_db ();

/* collect error messages */
$yb_errmsg = "";

/* if action not specified, presume view */
if ($action == "")
	$action = "view";

/* check for valid action */
if ($action != "view" && $action != "edit_entry" && $action != "save_entry" && $action != "add_entry" &&
    $action != "save_new_entry" && $action != "delete" && $action != "do_delete")
	$yb_errmsg .= fmt_errmsg("Unrecognized action '" . $action . "'.");

/* if title not specified, presume Welcome */
if ($title == "")
	$title = "Welcome";

/* parse the title: */

/* initially page type is set to this. if it is
 * still this later, it means the requested page
 * does not exist
 */
$pagetype = "none";

/* date pages */
if (ereg("^([A-Z][a-z]+)_([1-9][0-9]?)$",$title,$regs) &&
	valid_date (parse_month ($regs[1]),$regs[2],true)) {
	$month = parse_month ($regs[1]);
	$day = $regs[2];
	$pagetype = "date";
}

/* month pages */
elseif (ereg("^([A-Z][a-z]+)$",$title,$regs) &&
	parse_month($regs[1]) != 0) {
	$month = parse_month ($regs[1]);
	$pagetype = "month";
}

/* year pages */
elseif (ereg("^([1-9][0-9]*)(_BC|)$",$title,$regs)) {
	$pagetype = "year";
	if ($regs[2] == "_BC")
		$year = get_ay("BC",$regs[1]);
	else
		$year = get_ay("AD",$regs[1]);

}

/* century pages */
elseif ((ereg("^([0-9]?1)st_century(_BC|)$",$title,$regs) ||
	 ereg("^([0-9]?2)nd_century(_BC|)$",$title,$regs) ||
	 ereg("^([0-9]?3)rd_century(_BC|)$",$title,$regs) ||
	 ereg("^([0-9]?[04-9])th_century(_BC|)$",$title,$regs)) &&
	!ereg("^0",$regs[1]))
{
	$pagetype = "century";
	if ($regs[2] == "_BC")
		$century = 1-$regs[1];
	else
		$century = $regs[1];
}

/* other pages */
elseif ($title == "Centuries") 
	$pagetype = "centuries";
elseif ($title == "Welcome")
	$pagetype = "welcome";
elseif ($title == "Months")
	$pagetype = "months";

/* invalid page title */
else
	$yb_errmsg .= fmt_errmsg("No such page '" . fmt_title ($title) . "' in Wikipedia Yearbook.");

/* output the requested page */
if ($yb_errmsg != "")
	do_error_page ($yb_errmsg);
elseif ($action == "view" && $pagetype == "date")
	view_date_page ($month,$day);
elseif ($action == "view" && $pagetype == "month")
	view_month_page ($month);
elseif ($action == "view" && $pagetype == "year")
	view_year_page ($year);
elseif ($action == "view" && $pagetype == "century")
	view_century_page ($century);
elseif ($action == "view" && $pagetype == "centuries")
	view_centuries_page ();
elseif ($action == "view" && $pagetype == "months")
	view_months_page ();
elseif ($action == "view" && $pagetype == "welcome")
	view_welcome_page ();
elseif ($action == "edit_entry")
	edit_entry ($id);
elseif ($action == "save_entry")
	save_entry ($id);
elseif ($action == "add_entry")
	add_entry ();
elseif ($action == "save_new_entry")
	save_new_entry ();
elseif ($action == "delete")
	delete ($id);
elseif ($action == "do_delete")
	do_delete ($id);


/* End of file */
?>