#! /usr/bin/zsh
# vanquish: build Solaris packages from simple spec files
# Copyright (C) 2007 River Tarnell <river@attenuate.org>.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely. This software is provided 'as-is', without any express or implied
# warranty.

# $Id$

errexit() {
	echo $* >&2
	exit 1
}

tryrun() {
	if [ -x $ROOT/rc.$1 ]; then
		echo "+ rc.$1 ..."
		$ROOT/rc.$1 $TMPDIR/install || errexit "$0: failed to run rc.$1"
	fi
}

gnubuild() {
	tryrun preconfigure
	CC=cc CXX=CC CFLAGS="-xO3 $pkg_cflags" 					\
		CPPFLAGS="-I/opt/wmf/include $pkg_cppflags"			\
		LDFLAGS="-L/opt/wmf/lib -R/opt/wmf/lib $pkg_ldflags"		\
		$pkg_confprog --prefix=/opt/wmf ${=pkg_confargs} || errexit "$0: configure failed"
	tryrun postconfigure
	tryrun prebuild
	gmake DESTDIR=$TMPDIR/install || errexit "$0: build failed"
	tryrun postbuild
	tryrun preinstall
	gmake DESTDIR=$TMPDIR/install install || errexit "$0: install failed"
	tryrun postinstall
}

if ! [ $# = 1 ]; then
	echo "$0: wrong number of arguments" >&2
	echo "$0: usage: $0 <pkginfo>" >&2
	exit 1
fi

ROOT=`pwd`
TMPDIR=`pwd`/buildpkg.$$
INFO=$1

cleanup() {
	cd $ROOT
	rm -rf $TMPDIR
}

trap cleanup 0 

{ mkdir $TMPDIR && cd $TMPDIR } || errexit "$0: cannot create $TMPDIR"

if ! [ "$INFO[0]" = / ]; then
	INFO="$ROOT/$INFO"
fi

[ -r "$INFO" ] || errexit "$0: cannot read $INFO" 

pkg_patches=""
pkg_confargs=""
pkg_confprog="./configure"

< $INFO while read cmd rest; do
	case $cmd in
		name) pkg_name="$rest";;
		desc) pkg_desc="$rest";;
		version) pkg_version="$rest";;
		src) pkg_src="$rest";;
		srcdir) pkg_srcdir="$rest";;
		patch) pkg_patches="$pkg_patches $rest";;
		configure) pkg_confargs="$pkg_confargs $rest";;
		confprog) pkg_confprog="$rest";;
		ldflags) pkg_ldflags="$rest";;
		cflags) pkg_cflags="$rest";;
		cppflags) pkg_cppflags="$rest";;
		url) pkg_url="$rest";;
		*)
			errexit "$0: $INFO: unknown directive \"$cmd\""
			;;
	esac
done

[ -z "$pkg_name" ] && errexit "$0: $INFO: no name given"
[ -z "$pkg_desc" ] && errexit "$0: $INFO: no description given"
[ -z "$pkg_version" ] && errexit "$0: $INFO: no version given"
[ -z "$pkg_src" ] && errexit "$0: $INFO: no src given"
[ -z "$pkg_srcdir" ] && errexit "$0: $INFO: no srcdir given"

[ -r "$ROOT/$pkg_src" ] || {
	[ -z "$pkg_url" ] && errexit "$0: source archive $pkg_src does not exist and no URL given"
	echo "+ download $pkg_src ..." >&2
	/usr/sfw/bin/wget "-O$ROOT/$pkg_src" "$pkg_url" || errexit "$0: cannot download"
}

echo "+ extract $pkg_src ..." >&2
if [ "$pkg_src[-4,$#pkg_src]" = ".bz2" -o "$pkg_src[-5,$#pkg_src]" = ".tbz2" ]; then
	{ bzip2 -dc $ROOT/$pkg_src | gtar xf - } || errexit "$0: cannot extract"
else
	{ gzip -dc $ROOT/$pkg_src | gtar xf - } || errexit "$0: cannot extract"
fi

cd $pkg_srcdir || errexit "$0: cannot chdir"

for patch in ${=pkg_patches}; do
	echo "+ apply $patch ..." >&2
	/usr/local/bin/patch -p1 <$ROOT/$patch || errexit "$0: cannot apply $patch"
done

gnubuild
cd $TMPDIR
{ pkgproto `pwd`/install=/ | grep -v /opt/wmf/share/info/dir >prototype } || errexit "$0: cannot generate prototype"
echo "i pkginfo" >>prototype
cat >pkginfo <<EOF
PKG=$pkg_name
ARCH=`uname -m`
VERSION=$pkg_version
NAME=$pkg_desc
CATEGORY=application
BASEDIR=/
EOF
pkgmk -o || errexit "$0: cannot build package"
ds="${pkg_name}-${pkg_version}.`uname -m`.pkg"
pkgtrans -s /var/spool/pkg "`pwd`/$ds" $pkg_name || errexit "$0: cannot transfer package to datastream"
mv $ds ..
cd ..
ls -l $ds
